### ISSUE TITLE
Improvements to the permission workflow

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#100]
After using the platform for a while, we would like to request a modification in this regard, to better fit the needs of our users.

 

The idea is not to change the workflow per se, in the sense that it should still work according to the following steps:

1.    user uploads a layer related to a specific group. Only the manager of the said group and admins can see it and update metadata

2.    the manager of the said group approves the layer

3.    admins are informed and publish the layer

4.    the layer is public.

 

The only difference would be that in step 1, all the members of the said group should be able to see the layer and not only the manager. The manager of the said group should be able to see it and change the metadata (like it is now). This will be more in line with the idea of having a working group and building an online community.

**Comment by afabiani** [comment]
@meyerch I deployed on IHP-DEV the improvements you requested. Now the group members can see published layers. Also now it is sufficient to give "view" permissions to the Group in order to make the layer accessible. Also I gave more powers to the Group Managers.

Please let me know if those changes match what you requested.

**Comment by meyerch** [comment]
Hi, just to let you know that I am currently testing this task. Will update you as soon as possible

**Comment by meyerch** [comment]
Hi, down below are some comments on the workflow, which does not match what was required.  Please note that all that is said below applies also to Maps and to Documents. 

1/ Problem: When a user uploads a layer without linking it to a specific group in the metadata, then all the managers can see it in the layers’ list with the “pending approval” mention (screenshot 1) but cannot access it (screenshot 2). 
For example, Najet.guefradj (member of group “Them 6: Water education”) uploads a layer without filling the metadata. Nonetheless, all the managers of all groups can see her layer in the layers’ list.
![layersList_pendingApproval.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e495832690908586faab7cb458fe90204820523914b1246684ef6af3006b1300051bff054a5556f9f0d87fa2b33826dc0d0eefd43b5f74c53d15acb98719bd13a632c91edbe2e3d7158abd7f37ed998e48341f00198efb5a30a59f42cf51ff59ac.PNG)
![LayerPendingApproval_notAccessible.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46c495832690b3ac81edb64da37ce0843b493172253bad2464a4e02bba5168080d031bbe5d4a1f06a3a3dc78e2a436628f555ab9d5685b22906c14aebdd41fbf02ba248b4e80b0be9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec95ff24ce4485da2133f63f43b.PNG)

**Comment by meyerch** [comment]
@afabiani  
I just checked with Youssef for the default permissions of the manager. 
So, as it is now is perfect. No need to change anything else. 

Then, this task is accepted

**Comment by meyerch** [comment]
@afabiani 
Sorry, I have to request another change....
So this night I realised that the manager needs to be able to change the metadata to "approve" the layer, since the "is approved" tick is located within the metadata. 

Thus, to avoid complicated communication between a manager and his group members, can you change the default permissions of layer/document/map so that: 
by default, the group manager is allowed to change the metadata of the layer/map/doc ?

Thank you

**Comment by afabiani** [comment]
@meyerch it should be already like this.

I'm going to redo the test case again, but I'm pretty sure the managers can edit the metadata.

**Comment by meyerch** [comment]
Ok I just rechecked. Nevermind what I was saying, I got confused.
Sorry about that

**Comment by meyerch** [comment]
Then, this task is accepted, and I will archive it. Thanks again for your swift work on this
