### ISSUE TITLE
[Time Series] Upload form prevents to use CAPS on the file names

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#107]
Currently when trying to upload a layer, the system is not able to recognize its name correctly when CAPS letters appears on the file names.

**Comment by ricardogsilva** [comment]
A fix for this is ready for testing at https://github.com/ricardogsilva/geonode/commit/b3b71eb7393462a6ede11d81d973994eff4f759e

**Comment by ricardogsilva** [comment]
Made one extra change

https://github.com/geosolutions-it/geonode/commit/f862ef6dc687f7f1bc07b21d2d1fd8dbfc4e7c3a

**Comment by meyerch** [comment]
accepted and archived
