### ISSUE TITLE
[Time Series] Upload form prevents to upload ZIP files

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#108]
Currently - most probably a misconfiguration - the Layer Upload form does not allow to send ZIP files.

**Comment by ricardogsilva** [comment]
A fix for this issue is in https://github.com/geosolutions-it/geonode/commit/7dcc9a4bfde8051f875c9915442925eb2816e45f

**Comment by meyerch** [comment]
it works perfectly for the vector layer (shapefiles and files that come along + .sld).

However, I have trouble with uploading zipped file of raster (.GeoTif + .sld). I end up with this error message every time:
![upload_raster_zip.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fd84962c8387969de8ac57a14fcf8e2056653f6b14b1247a80e03cfd183954560e1aa8445c0912adfc8b2ef0b63c738a580becd46b5d66da2f53fde6d640e258f075c95d8fa4bd8246c1ed3f24e38c8a4b3d18051f80ed10.PNG)
For the record, I tested the upload of zipped rasters with the [geotfif + .sld] that were successfully uploaded in issue #109

**Comment by meyerch** [comment]
fixed and accepted.
