### ISSUE TITLE
[Task for #91] Multiple email addresses for non-registered users

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#112]
closes #91

**Comment by meyerch** [comment]
Thanks, it works now: invitations can be sent to several email addresses at once. 

Can you just specify on the page (http://ihp-wins-dev.geo-solutions.it/invitations/geonode-send-invite/) the maximum number of email addresses that can be entered into the field? 
In English,  it would say: "(Max. 200 email addresses)" 
In French, it would say : "(Max: 200 adresses e-mail)"

Something like this (see highlighted in yellow):
![max_email_addresses.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e595821c878ea886e58042a059e2913a5522606b48e13b628ae92dbc56395b4d5a47fd155c5a40aaafd82ea4b36a708a5f0be9d16c5a72c42f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e68c8b473c1d011f88ff5f27ed.PNG)

**Comment by meyerch** [comment]
Similarly to the above comment, can you please update the text in the User Menu (the one that appears when the user clicks on his name in the upper right corner). 
The idea is to put the "Invite user" in a plural form to match the fact that several persons can be invited at once. 
In English, we should have: "Invite Users"
In French, we should have: "Inviter des utilisateurs"

![invite_users.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e19a8c2a9686969afaba51b71fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8228b4584b3bd8d48c9eb3f22e78e89482c53.PNG)

**Comment by afabiani** [comment]
@meyerch Done!

**Comment by meyerch** [comment]
thanks
accepted
