### ISSUE TITLE
[Time Series] Upload form prevents to upload CSV files

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#115]
Following my comment on struggling to upload .csv (see task #47), please find attached the 2 .csv files I tried to upload (unsuccessfully) on the dev instance.

[iwa_city_charges_test_wins.zip](https://github.com/geosolutions-it/unesco-ihp/files/1677226/iwa_city_charges_test_wins.zip)

**Comment by ricardogsilva** [comment]
A fix for this is ready for testing at https://github.com/geosolutions-it/geonode/commit/7dcc9a4bfde8051f875c9915442925eb2816e45f
