### ISSUE TITLE
"Search" tool issue

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#116]
Searching through the search tool ends un with a blank list. It seems that the system retrieves objects but do not show them: 
- No number are indicated next to "Found"
- However, in the menu on the left, the number of layers retrievedd is correctly indicated in the "Catergories", "Type"

Searching for "Coastal aquifer in the mediterranean region": 
![search.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb919b31818bebc3abaf51ab57f5973d047d317c5da22f24d0b72eb9432e535a094eac42585b44fdfc8f29b4aa2e32db025fb28c341521842f1bbeba8215be04bb278e4f86b7bf884ac8ef2f68.PNG)

**Comment by afabiani** [comment]
@meyerch this should be fixed now. Please try again when you have time.

**Comment by meyerch** [comment]
yes it works now. Thank you
Accepted
