### ISSUE TITLE
[Task for #91] Change e-mail message

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#117]
For People Invitations
-----------------------------
I have one last general change to require, about the invitation email that people will receive.
After testing it, I realized that non-manager members of WINS can also invite people to join WINS (which is absolutely normal and ok). So the message needs to be slightly updated. Sorry about that, I should have thought ofit before.

1/ I would like to change the part that was reading "xxx.xxx manages the following group(s):" for "xxx.xxx is a member of the following group(s)".
This means that in the case of managers, the list include all the groups they are part of whether as a manager or as a simple member.
As for non-manager users, it means that there is a list of all the group(s) they are a member of.
For example, for gabin.archambault, the list would say "Theme 6: Water education" and "Theme 2: Groundwater". For najet.guefradj, the list would say"Theme 6: Water education"

2/ I noticed that some links are misplaced and there are some errors in the text. Below is the definitive version for the text. In brackets are special text, i.e. links or image; I have defined them at the end out of clarification (in the current invitation, only 1 link is incorrect)
Please display the same thing as what is within the quotation marks (see in the next message a picture of the final result):

"
English / Français

Dear Sir/Madam,

gabin.archambault is inviting you to join the Water Information Network System ([ihp-wins-dev.geo-solutions.it]).

To do so, please register at [IHP-WINS Registration].

Once you receive the confirmation that your account is activated, you can notify gabin.archambault that you wish to join her/his group(s) through [this link].

gabin.archambault is a member of the following group(s):
•	[IHP-Theme6-Water-education]
•	[IHP-Theme2-Groundwater]

We look forward to seeing you on the platform,

The IHP-WINS team
[Electronic signature]

Madame, Monsieur,

gabin.archambault vous invite à rejoindre le Système de Réseau d’Information sur l’Eau ([ihp-wins-dev.geo-solutions.it]).

Pour cela, merci de vous enregistrer sur [Inscriptions IHP-WINS].

Une fois reçue la confirmation d’activation de votre compte, vous pouvez informer gabin.archambault que vous souhaitez rejoindre son(ses) groupe(s) via [ce lien].

gabin.archambault est membre du(des) groupe(s) suivant(s):
•	[IHP-Theme6-Water-education]
•	[IHP-Theme2-Groundwater]

Au plaisir de vous croiser sur la plateforme,

L’équipe IHP-WINS
[electronic signature]"

Here are the links
[ihp-wins-dev.geo-solutions.it]: ihp-wins-dev.geo-solutions.it (this one is correctly working already in the current invitation)
[IHP-WINS Registration]/[Inscriptions IHP-WINS]: http://ihp-wins-dev.geo-solutions.it/account/signup/ (this link in wrong in the current invitation)
[this link]/[ce lien]: link to the pre-filled message on WINS with the inviting person as reicpient (this link is correctly working in the current invitation)
[IHP-Theme6-Water-education] & [IHP-Theme2-Groundwater] & etc : link to the designated group. This is working fine in the current invitation.

![68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3539633930636539633233353566303031316564326539302f313235353136633636653832633732386163 3](https://user-images.githubusercontent.com/1278021/35692791-886822c0-077c-11e8-9c73-52fce37c89e3.png)

![68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3539633930636539633233353566303031316564326539302f313235353136633636653832633732386163 2](https://user-images.githubusercontent.com/1278021/35692798-8c5b422c-077c-11e8-9ef1-097f67216dea.png)

**Comment by afabiani** [comment]
@meyerch can you test again?

If you want to send invitations to the same addresses, just go to

http://ihp-wins-dev.geo-solutions.it/admin/invitations/invitation/

and delete the old ones.

**Comment by meyerch** [comment]
Thanks for updating the email.
i have 3 comments on the text of the email invitation. See the screenshot of the email invitation for the location of those issues.
 
1/ The subject of the email starts with the URL of the platform (highlighted in blue)
--> can you delete this URL so that the subject starts with the name of the inviter? If for some reasons the URL has to be in the subject, then can you at least move it to the end of the subject? 
...
...
2/A hyperlink missing (hihlighted in yellow). This applies to both the ENGLISH and FRENCH parts of the message.
--> On the "ihp-wins-dev.geo-solutions.it" text, please add a hyperlink that refers to ihp-wins-dev.geo-solutions.it
...
...
3/ A hyperlink is wrong (highlighted in green). This applies to both the ENGLISH and FRENCH parts of the message. 
--> the "IHP-WINS Registration" ("Inscriptions IHP-WINS" for the French part) contains a hyperlink that links to a page not found. 
--> Please correct the hyperlink so that it links to http://ihp-wins-dev.geo-solutions.it/account/signup/

![MailInvitation_text.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46c595932fab8dbf86fdbe57ad52feab3d433f676b48e13b628ae92dbc56395b4d5a47fd155c5a40aaafd82ea4b36a708a5f0be9d16c5a72c42f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e68c8a493b1d051f81ff5427ed.PNG)

**Comment by afabiani** [comment]
@meyerch please see comments below:

1/ This is a feature of DJango core. It by default puts the site name on all e-mail notifications that get created. It is odd but changing this behavior is not actually that easy and requires some deep investigation. I'm going to open a separate issue for this and I will put it on the backlog.

--------------------------------------------
2/ This has been fixed. Please try again.

--------------------------------------------
3/ Normally you shouldn't reach a "Page not found" but redirected to the signup page. The page not found happens only if you delete the Invitation record from the Admin dashboard.
Let me explain better how this works and then you can decide how to change this.

- When the system sends an invitations to a user, it creates a new record and associates a "key" to it
- Into the email the "invite url" contains the "key". When the user clicks on it basically the system does:
a) Looks for the associated key and updates the invitation to "Accepted"
b) Redirects the user to the account/signup page

If we change the link directly to account/signup you won't be able to know if the user accepted the invitation or not.

I did several tests and currently, if the invitations are present on the DB, I am always redirected to the account/signup page; so at this time I could not reproduce the issue (by following the correct workflow).

Can you please try again with fresh new invitations and without removing them from the DB before clicking on the URL?

Another possibility, of course, is to change the URL to account/signup being sure that no redirection of any kind will be applied, but the invitation won't be updated to "accepted". If you do not care about this feature, I can easily change the URL as you mentioned on the previous comment.

Please let me know how to proceed.

**Comment by meyerch** [comment]
Thanks for the quick response.  I am follwing the points you mentions: 
1/ Ok. For now it is not a priority, especially if it is going to take some times. 
---
2/ The text of the message is fine now. Thanks. 
---
3/ I understand better now. I did as you advised and the link worked correctly. 
However, after discussion with Youssef, I still prefer that you change the link (n both English and French parts) simply to account/signup 
At least it will ensure that if invitees click the link and decide to come back later to fill the form and actually register, then the linnk within the email will still work. 
For now, we don't see it as a problem not to be advised on who accepted the invitation. In any case, we can still compare the emails on the invitation list to the email in the user list in the admin interface. 
---> so please just do the hyperlink on http://ihp-wins-dev.geo-solutions.it/account/signup/

**Comment by afabiani** [comment]
@meyerch done.

After a bit of investigation, I have fixed also 1/. Even if gmail has cached the old subjects, I tested with another account and now the [sitename] prefix has disappeared from the subject.

The side effect is that now all the notifications from the platform, won't have the [sitename] prefix anymore. In case you will do further tests, please check also on SPAM folder.

**Comment by meyerch** [comment]
Thanks for the feedback.
This task is complete and accepted
