### ISSUE TITLE
[Task for #91] Group names instead of slugs

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#118]
For People Invitations
------------------------------

In the list of group(s) the inviting user is member of, it is not the group names that are displayed but the group slugs.
For instance, the "Theme 6: Water Education" is the name of the group, but what is displayed is the slug which is "IHP-Theme6-Water-education".
Sometimes (especially when the group has a long name), the slug is really different from the name of the group.
Is it possible to display the actual group name, and not the group slug?

**Comment by afabiani** [comment]
@meyerch can you test again?

If you want to send invitations to the same addresses, just go to

http://ihp-wins-dev.geo-solutions.it/admin/invitations/invitation/

and delete the old ones.

**Comment by meyerch** [comment]
Perfect, thanks.
![mailInvitation_groupName_OK.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e595932fab8dbf86fdbe57ad52feab2e542866392aa22675bacc03fd0e39111d0014f9121c4d4eeefc807af2b23974dc0a5ae8d3680974c63e11a8b8831ab903a83c990dd4e8e8d51199a26867f5819d4e3914041d88f85833a39d4ccd5cf648f300.PNG)

I am archiving this one
