### ISSUE TITLE
Issue with 'Zoom by dragging a box' in View Map

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#120]
I noticed a bug with the 'Zoom by dragging a box' button that is above the viewer when viewing or creating a map (here for instance: http://ihp-wins-dev.geo-solutions.it/maps/new?layer=geonode:paratf_male )

The issue is that when I click on the 'Zoom by dragging a box' button, I cannot unclick it. 
I am left with the box dragging tool, and have to refresh the page to deactivate it. 

--> can you make sure that one click on the "'Zoom by dragging a box' button activate it, and that another click on it deactivate it.

Location of the button:
![ZoomBox_viewMap.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46d29b952ea08cb1b0ffb646b370f1846b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84b1b68b49c1ef3823e1838c473c1d0c0ac4.PNG)

**Comment by afabiani** [comment]
@meyerch done.

**Comment by meyerch** [comment]
Thanks a lot.
Accepted and closed
