### ISSUE TITLE
Issue in the Printing: License text

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#121]
I noticed an error in the text of the Lisence, on the outcome PDFs when using the Printint tool. 

For now, it states that: 
" Sharing data with WPDx does not impact or change [....]"
--> Please replace "WPDx" with "IHP-WINS" it so that it says:
"Sharing data with IHP-WINS does not impact or change [....]"

It also states that: 
"The original holder remains the owner even after the data is shared."
--> Please replace "owner" with "responsible" so that it says "The original holder remains the responsible even after the data is shared."
It will also be back in line with the metadata, since we replace 'owner' with 'responsible' there. 

![print_licence.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d96bca586eaba4da758b2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b4bc5ee3520e68d8a4d3c0c48.PNG)

Thank you.

**Comment by afabiani** [comment]
@meyerch done. Please double check.

**Comment by meyerch** [comment]
Fine, thank you
Accepted
