### ISSUE TITLE
Issue with zoom in print preview/outcome PDF

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#122]
I noticed a new bug with the zoom in te print preview/outcome PDF. Basically, for 2 levels of zoom, there is a mismatch between what the print preview shows and the oucome PDF. 
Could you please fix it? 
See explanations below. Out of clarity, I am creating 1 message per example. 
Let me know if you have any questions.

**Comment by meyerch** [comment]
1/ This level of zoom seems to work correctly: the outcome PDF is exactly what is shown in the viewer. 
Note that in the viewer, the scroll-down zoom menu is at 1:75,000. and the scale shows 1000km <--> 500 mi

![zoom1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f29b952ed3c1e5cdf9ad4cae58f3806b1c65267005a77f25d1e52ebe172954095f4eaf415c5f45f9ff8b39baa47e21d40854b088270a36d43703adb1881eba00bd25834e84b6b98c4dc5fa70.PNG)

**Comment by meyerch** [comment]
2/ Now, in the print preview, I zoom in 1 time, using the "+" of the scale on the left. 
As you can see, it effectively zooms in in the print preview, and it now shows 500km/200mi on the scale. 
However, you will notice that the scroll-down scale menu still shows "1:75,000" (same as in the ZOOM 1). 
Plus, the outcome PDF does not match the zoom in the print preview. The outcome PDF is the same as the one in the ZOOM 1
![zoom2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f29b952ed0c1e5cdf9ad4cae58f3806b1c65267005a77f25d1e52ebe172954095f4eaf415c5f45f9ff8b39baa47e21d40854b088270a36d43703adb1881eba00bd25834e80b1b8884cc1fa70.PNG)

**Comment by meyerch** [comment]
3/ Now, I zoom in one more time, using again the  "+" of the scale on the left.
As you can see, it effectively zooms in in the print preview, and it now shows 200km/100mi on the scale. Now, the drop-down scale menu shows "1:35,000,000".

However, there is 1 issue :
- the outcome PDF does not match the zoom in the print preview. The outcome PDF is the same as the one that I was expected for zoom 2 (i.e the outcome PDF of ZOOM 3 is actually the printpreview of ZOOM 2)

So again, there is a mismatch between the what the print preview displays and the scale displayed in the scroll-down scale menu.

Please checkthat the scale displayed in the drop-down scale bar corresponds to what is shown in the printpreview (i.e this print preview actually shows a map with a scale of 1:35,000,000)
Also, ensure that the outcome PDF matches the printpreview in terms of zoom

![zoom3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f29b952ed1c1e5cdf9ad4cae58f3806b1c65267005a77f25d1e52ebe172954095f4eaf415c5f45f9ff8b39baa47e21d40854b088270a36d43703adb0881eba00bd25834d85bfba8f4dc8fa70.PNG)

**Comment by afabiani** [comment]
@meyerch at a very first look it seems that there is one zoom level on the print-preview that does not change the scale number. It should be just a configuration issue.
To make a try, when you click the "+" button on the preview, check that also the scale factor number changes accordingly.

**Comment by meyerch** [comment]
4/ I zoom in 1 more time. This time, everything is ok: 
The outcome PDF matches the printpreview. 

However, please check  that this printpreview corresponds to a scale of 1:10,000,000
![zoom4.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f29b952ed6c1e5cdf9ad4cae58f3806b1c65267005a77f25d1e52ebe172954095f4eaf415c5f45f9ff8b39baa47e21d40854b088270a36d43703adb0881eba00bd25834d8db1bf894ec9fa70.PNG)

**Comment by meyerch** [comment]
Hi @afabiani 
Yes, exactly. It looks like at one point, when I zoom in, the scale factor stays on 1:75,000,000. Which results in the mismatched PDF outcome

**Comment by afabiani** [comment]
@meyerch should be good now.

**Comment by meyerch** [comment]
@afabiani 
Now the scale factor number changes accordingly.

However, for 2 levels of zoom, there is still a mismatch between the printpreview and the outcome pdf. See the screenshot below:

![zoom1_mismatch.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f29b952ed3bca486fab242b05ef8d665043761260ea62864c7b96aea1b7a055b5a4afa17095a46f9af892ba5b638708b590defc3714d36976345f3e5db55ea43a82a994e82bcbd8f4dc7e03f21e38c8f483e1d1755.PNG)

![zoom2_mismatch.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f29b952ed0bca486fab242b05ef8d665043761260ea62864c7b96aea1b7a055b5a4afa17095a46f9af892ba5b638708b590defc3714d36976345f3e5db55ea43a82a994e8cbcbd8f4dc7e03f21e3838e4c3c1a1755.PNG)

**Comment by afabiani** [comment]
@meyerch uhm. Ok I think I understood. In order to make print preview matching the zoom tool, I need to always divide by 2 (more or less) the scale factors. I'm doing few configuration tests. Until now it looks good. Going to double check pdf at all zoom levels.

**Comment by meyerch** [comment]
I have checked pdf for all the other zoom levels and it works fine, except for those 2 mentionned above

**Comment by afabiani** [comment]
It depends on the factor between 2 zoom levels. Let me check now, it should be good. I will come back in a few.

**Comment by meyerch** [comment]
ok

**Comment by afabiani** [comment]
So this is until 1:12.500.000. Until it looks ok to me, what do you think? Going to test the higher resolutions too.

![2018-02-05 11_08_04-disability-adjusted life year attributable to paratyphoid fever in 2015 for 5-14](https://user-images.githubusercontent.com/1278021/35799357-b9dcb6ae-0a65-11e8-9d1c-d7c40ca66908.png)
![2018-02-05 11_09_02-unesco-ihp-wins-feb_5_2018 6 pdf](https://user-images.githubusercontent.com/1278021/35799361-bc0e2e12-0a65-11e8-80d1-54ccfe76ff5e.png)
![2018-02-05 11_09_28-disability-adjusted life year attributable to paratyphoid fever in 2015 for 5-14](https://user-images.githubusercontent.com/1278021/35799363-bdf7d7f0-0a65-11e8-8325-0cfa3056c38b.png)
![2018-02-05 11_09_49-unesco-ihp-wins-feb_5_2018 7 pdf](https://user-images.githubusercontent.com/1278021/35799365-c0ba076a-0a65-11e8-87e9-6f66848eed44.png)
![2018-02-05 11_10_09-disability-adjusted life year attributable to paratyphoid fever in 2015 for 5-14](https://user-images.githubusercontent.com/1278021/35799369-c2fc064a-0a65-11e8-861b-0952107161cc.png)
![2018-02-05 11_10_27-unesco-ihp-wins-feb_5_2018 8 pdf](https://user-images.githubusercontent.com/1278021/35799372-c5462048-0a65-11e8-9f51-27136e29ef75.png)
![2018-02-05 11_10_47-disability-adjusted life year attributable to paratyphoid fever in 2015 for 5-14](https://user-images.githubusercontent.com/1278021/35799374-c79855c8-0a65-11e8-9b60-e65dbbee454b.png)
![2018-02-05 11_11_09-unesco-ihp-wins-feb_5_2018 9 pdf](https://user-images.githubusercontent.com/1278021/35799378-c9538f54-0a65-11e8-99fc-b9af74ae7212.png)
![2018-02-05 11_11_45-disability-adjusted life year attributable to paratyphoid fever in 2015 for 5-14](https://user-images.githubusercontent.com/1278021/35799380-cb069c24-0a65-11e8-8409-b388f7dfa550.png)
![2018-02-05 11_12_02-unesco-ihp-wins-feb_5_2018 10 pdf](https://user-images.githubusercontent.com/1278021/35799382-ccce1186-0a65-11e8-8727-e55c66c45d24.png)
![2018-02-05 11_12_38-disability-adjusted life year attributable to paratyphoid fever in 2015 for 5-14](https://user-images.githubusercontent.com/1278021/35799387-d019f77e-0a65-11e8-8369-694ef9079f32.png)
![2018-02-05 11_12_57-unesco-ihp-wins-feb_5_2018 11 pdf](https://user-images.githubusercontent.com/1278021/35799388-d0f52a9c-0a65-11e8-85b1-e5c2b405ecd5.png)

**Comment by afabiani** [comment]
@meyerch unless I'm missing something, it seems to be good to me now. We can still tweak a bit with the scale factors number into the configuration file. Please let me know how it goes now.

**Comment by meyerch** [comment]
Ok, there is no longer a real mismatch between the PrintPerview and the outcome PDF. 

However, I fill that for almost all scale factors (except for 250,000,000 and 150,000,000) the difference between the PrintPreview and outcome PDF has increased. 
Before, the outcome PDF was almost excatly the same thing as the Printpreview, which was perfect.

 Now, the outcome PDF is less zoomed than what is shown in the PrintPreview. 
Is this what you can solve "by tweaking a bit the scale factors" ?

**Comment by afabiani** [comment]
Yes, it is a matter of trying to find scale factors that allows us to make the difference less visible. However, the difference is not on the scale number, but on the printed area. The PDF area is a bit wider in respect to the PrintPreviw window, so it is possible that you might have the impression that the picture are a bit different. I can spend some more time on this trying to find some more suitable numbers if you need.
In any case, with such constraint of dividing always by two, I guess it won't be possible to ensure a perfect result for all zoom levels.
A possible solution could be to remove the zoom slider and force the users to select the scale factor through the scale bar. In that case we can add our custom scale factors too.

Please let me know.

**Comment by meyerch** [comment]
At this stage, we need to go for the less time-consuming solution, since we need to deploy everything to the public instance in the upcoming days. 
So let me know wich one it is. 

Additional question: does deleting the zoom slider to only select scale through the scale bar will ensure that the outcome PDF will sow the same thing as in the Printpreview?

**Comment by afabiani** [comment]
It should, yes, I'm going to do a very quick test. I restored the original scale factors. Let's try to create PDFs by selecting the scale instead of using the zoom slider.

**Comment by afabiani** [comment]
before testing let me do some changes

**Comment by meyerch** [comment]
Sure. Let me know when it is ready.
Thanks

**Comment by afabiani** [comment]
@meyerch can you do a quick test with the first 4/5 scales and tell me if it is better now? Remember to use only the scale tool to change the zoom level

**Comment by meyerch** [comment]
ok, I am doing it now

**Comment by meyerch** [comment]
I tried the first 5 zooms in the scale tool. So far, I like it: (left: printPreview; right: outcome PDF)
![1_280.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46b9abc87bd2c1e5cdf9ad4cae58f3806b1c65267005a77f25d1e52ebe172954095f4eaf415c5f45f9ff8b39baa47e21d40854b088270a36d43703adb0881eba00bd28884f82b2bd8e4fc5fa70.PNG)
![1_140.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46b9abcb77d2c1e5cdf9ad4cae58f3806b1c65267005a77f25d1e52ebe172954095f4eaf415c5f45f9ff8b39baa47e21d40854b088270a36d43703adb0881eba00bd28884f82b2b4824dc5fa70.PNG)
![1_70.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46b9abcd73c0cfeb9ffbb049a15ee4d67304722a2800f77e2483e529ea102e075f5f4dac45585e41fafb9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abe06b2238b4880b2ba894fd2a5.PNG)
![1_35.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46b9abc976c0cfeb9ffbb049a15ee4d67304722a2800f77e2483e529ea102e075f5f4dac45585e41fafb9b37b4f46d2ede0356b49b381d66cc2f10abb2831abe06b2238b4883b6b48945d2a5.PNG)
![1_17,5.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46b9abcb74ced6ebc3abaf51ab57f5973d047d317c5da22f24d0b72eb9432e535a094eac42585b44fdfc8f29b4aa2e32db025fb28c341521842f1bbeb98515be04bb27834c85b1ba824dc3ed2f68.PNG)

**Comment by afabiani** [comment]
@meyerch I removed the zoom slider from the Print Preview panel. Now changing the zoom level is possible only by selecting the scale factor.

**Comment by meyerch** [comment]
ok, thanks

**Comment by meyerch** [comment]
accepted and closed
