### ISSUE TITLE
Removing the icons in "Categories" menu

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#123]
Is it possible to remove the icons that are in the "Categories" Menu?
So that there is only the name of the category, with no icon in front of it

![icon_categories2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e197952dbd80a89becb84cb654f5877b046b313916ac217586f76ae5002e580e0b4aa9450e0915f9fb8c7da6b63f708e5c0ae8d76f4d68d47f40f2ecdd42e64bef62994597b7b5804dc5e93a20ef8389493d1f07189bb2.PNG)

**Comment by afabiani** [comment]
@meyerch done.

**Comment by meyerch** [comment]
thanks. Accepted and closed
