### ISSUE TITLE
Adding a field in the Registration form

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#124]
Is it possible to add a  field in the registration form ?

1/The objectives are:

- to respond to this question: "Who recommended you IHP-WINS?" (in French: "Qui vous a recommandé IHP-WINS?"). Basically we want the registrant to enter the name of the person (if any) who recommended him to join WINS.
- the field should be non-mandatory (registrants can submit their registration form even if the field is left blank)
- the field should be free-text (50 characters max., spaces included)

Now that group managers have to invite users, the idea is for us to easily spot and activate new accounts if they are based on a recommandation from a member of WINS

What I have in mind:
![recommandation2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fa91992c8f8ea881edbe57ad52fec66b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84beb68b49c1ef382ce48b8b483b1d030ac4.PNG)

2/ This new field should be reflected in the "People" section on the Admin interface.
On http://ihp-wins-dev.geo-solutions.it/admin/people/profile/, is it possible to add a column on the right, titled "recommandation", which show the info entered in the new field from the registration form?
![recommandation.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fa91992c8f8ea881edbe57ad52fed665043761260ea62864c7b96aea1b7a055b5a4afa17095a46f9af892ba5b638708b590defc3714d36976345f3e5db55ea43a82a994e8cbcbd8f4dc7ed3427e08c88483f1a1755.PNG)

**Comment by afabiani** [comment]
@meyerch done.

**Comment by meyerch** [comment]
@afabiani 
Thanks!
Accepted
