### ISSUE TITLE
Emails received when user account is activated/notifications

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#126]
When inviting users to join the platform, I realised that there is a problem with the notifications emails the new user receives when his account is activated. Sorry I miss this issue before. 

So, at the moment, when a user account is activated by an Admin, the user automatically receives 2 emails: 
-	One to notify him of the activation of his account (current subject: “Your account is now active”)
-	One on how to manage notifications (Current subject: “IHP-WINS Notifications/Notifications IHP-WINS”)

--> 
1/Can you deactivate the automatic sending of the email on notifications? As a result, newly activated users only erceive 1 email on the activation of their account.

2/ Can you replace the text of the current activation email with the following (including the subject)? See message below for the text

3/ For now, when a user registered, all the email notifications are ticked. This is the default behavior. 
Can you ensure that the default behavior is the opposite: i.e. when a user registered, all his email notifications are unticked? 

Thank you.

**Comment by meyerch** [comment]
[Subject:] Welcome to IHP-WINS/Bienvenue sur IHP-WINS

Dear contributor,

Your account ([insert username]) has been approved and is now active on the Water Information Network System.
You can now log in to http://ihp-wins.unesco.org

To manage your account, please go to http://ihp-wins.unesco.org/notifications/settings/. 

The IHP-WINS Team

----------------------------------------------------------

Cher contributeur,

Votre compte ([insert username]) a été approuvé et est désormais actif sur le Système de Réseau d’Informations sur l’Eau.
Vous pouvez dès à présent vous connecter sur http://ihp-wins.unesco.org. 

Pour gérer votre compte, rendez-vous sur http://ihp-wins.unesco.org/notifications/settings/.

L’équipe IHP-WINS

**Comment by afabiani** [comment]
@meyerch done.

**Comment by meyerch** [comment]
Thanks a lot!

Some minor corrections:
1/ In the French version, please add the hyperlink to "http://ihp-wins-dev.geo-solutions.it" (see in green)
2/ In the French version, please add the  ")" that is missing after the username (see in yellow).  
3/ In both version, please add the hyperlink "http://ihp-wins-dev.geo-solutions.it/notifications/settings/" (see in blue)

![mail.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e595932fc0cfeb9ffbb049a15ee4d67304722a2800f77e2483e529ea102e075f5f4dac45585e41fafb9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abe06b3218e4a87b3bb8c4bd2a5.PNG)

**Comment by afabiani** [comment]
@meyerch I guess should be good now

![image](https://user-images.githubusercontent.com/1278021/35857911-dbec44f0-0b3a-11e8-854e-0c3269c33fed.png)

**Comment by meyerch** [comment]
perfect, thanks
Accepted and closed
