### ISSUE TITLE
Forgotten password - PROD instance

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#128]
Hi @afabiani,

On the PROD instance, there is an issue when a user tries to login and request a new password because he has forgotten his: 

After clicking "forgotten password" and then entering the email address to which the new password should be sent, users end up on a "bad getaway" page. 

Please solve this so that everythin flows correctly and forgotten password are sent to users.

**Comment by meyerch** [comment]
[Uploading password_forgotten.PNG...]

**Comment by afabiani** [comment]
@meyerch can you please try again now?

**Comment by meyerch** [comment]
It works now, thanks

**Comment by meyerch** [comment]
hi @afabiani 
this issue is also on the DEV instance. Can you fix it please?

**Comment by afabiani** [comment]
@meyerch Done.

**Comment by meyerch** [comment]
thanks. Accepted
