### ISSUE TITLE
Changing "owner" to "responsible" - PROD issue

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#129]
Hi @afabiani, 

I just noticed that we forgot to change an "owner" word to "responsible" some place: 
On a layer's page, map's page, document's page, in the 'about' section (on the right), there is still the word "owner" that appears, although we changed it for "Responsible" in the metadata. 

Thus, can you make sure that in this section on each layer/doc/map page, 'owner' is replaced by 'responsible" ? 

On the French version, everything is fine : "responsable" is displayed in this section. 
Thanks!

**Comment by meyerch** [comment]
![owner_layer's.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e783942690bca58ef0ba51e34eb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b45c0eb3f26ef8d8b473e0c48.PNG)

**Comment by afabiani** [comment]
@meyerch should be fine now, can you please check?

(I pushed changes in PROD for now, will backport on DEV also as soon as this is accepted)

**Comment by meyerch** [comment]
thanks a lot !
accepted
