### ISSUE TITLE
Check missing legend in WMS Remote layer page

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#131]
Legend doesn't show inside WMS remote layer page.
E.g. http://ihp-wins-dev.geo-solutions.it/layers/OSM-WMS

(which has a legend available: http://ows.mundialis.de/services/service?LAYER=OSM-WMS&TRANSPARENT=TRUE&SERVICE=WMS&REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&WIDTH=20&HEIGHT=20)

connected to #49

**Comment by afabiani** [comment]
Generally speaking it works, but it really depends on the remote service capabilities.

As an instance proxyfied OSM services do not make available the Legend for all layers.
