### ISSUE TITLE
PROD instance - Unable to upload .sld

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#134]
Hi @afabiani and @giohappy, 

I am facing a new issue on the PROD instance. 
Svereal contributors have reported issues with  uploading .sld files because of an error message. 
Whenever I tried to do upload .sld, I got the following message : 

![uplaod_sld.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fd8496228d87969ce5bb01e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b22a8a4a87b2be8b44c8ef3521e08c9d02.PNG)

Can you please solve this?  Thank you.

**Comment by giohappy** [comment]
hi @meyerch 
we are going to take charge of it today

**Comment by afabiani** [comment]
@meyerch @giohappy fixed

**Comment by meyerch** [comment]
thanks for the swift fix!
