### ISSUE TITLE
Display after upload of item - new window post geo-server configuration

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#135]
Hi @afabiani, 

I have noted a change and issue when uploading some items (time series, csv, etc.: anything that require some configuration steps after having uploaded the item).

Basically, the "Continue" button now leads to openning a page in a new window and no longer staying on the same tab (see screenshots)

Can you make sure that the "Continue" or "Done" buttons after having uploaded an item leads to a new page that opens on the same tab ? and not a new page that open in a new window. 

Thnaks

The button I am talking about: 
![configuration_geoserver_newwindow_csv.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46eb9b94258b84bc9de8ab4aab53cf932c4934763b12a6394f8be63fa84b7505001821ff021e4d58eeb9cb74fce36f34985619e8d83c0b70c33947fae9871dba57ba20884f81b6bd8f4ac2fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e64d53a1153e65e070346e0a.PNG)

The new window that opens up:
![configuration_geoserver_newWindow_timeserie.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46eb9b94258b84bc9de8ab4aab53cf932c4934763b12a6394f8be63f884b7505001821e818050a07a9bbd07eb4aa2e30c80351b882294d7ed43818fdec861abb57ec718e4d80e0bc8a4fc0ec3d24e28d8d5d220c4749d7ab0268f9d31e8a4afc59e0455fa5163464e670337a4e9616722c792a.PNG)

**Comment by afabiani** [comment]
@meyerch done!

**Comment by meyerch** [comment]
Hello @afabiani ,  

I still have the issue, after GeoServer configuration for time serie and csv. 
For non-TimeSerie layers, kml, and raster, I don't have the problem though.

![new_window.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e6918d1c958aa78be6a801e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b32a8a4a87b1b8834bc1ea3423ef8d9d02.PNG)

**Comment by afabiani** [comment]
@meyerch I changed the Javascript so I guess you need to cleanup your browser cache in order to see the updated version. Please let me know.

**Comment by meyerch** [comment]
I cleaned the cache the first time but cleaned it again and checked, and it works fine now. Thanks. 

I am archiving this one
