### ISSUE TITLE
What does "edit data" do?

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#136]
I noticed a new tab when clicking on "Edit layer" on a layer's page : 'Edit data' (or 'Modifier' in French). 
The point is that this button leads to opening the layer in a map interface. 
Is it normal? What is 'Edit data' for?

The 'Edit data' button : (http://ihp-wins-dev.geo-solutions.it/layers/geonode:paratf_fem)
![Editdata_createnew map.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46cd9093378682bd8ed6bc51a15ce491274330332405b3693cc7f33ab0487e021b4d44be44510e10f8fc8d7df0e739728f0a0bedd26d5b74c73817aeaa9e0dfd50e474d412dcfce9c85ecafa3c2ced8a8a4d391e031e89fa5f37a19d5985.PNG)

The page it leads to: (http://ihp-wins-dev.geo-solutions.it/maps/new?layer=geonode:paratf_fem)
![Editdata_createnew map2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46cd9093378682bd8ed6bc51a15ce491274330332405b37932c9a138ad4d71040c1b5ca6535d5615a8fd8c2ff0e06d7588595dedd16e5f70c63c14aaba9003ad43eb7edf10d8eff6df0ed2e22f24ef818e4a3c19051e8ffe5c30a2994bda15.PNG)

**Comment by afabiani** [comment]
@meyerch this is meant to allow a user to edit the layer data.
It is currently using the same interface of the maps. If you notice there's an "Edit" button on the toolbar which allows you to modify the geometries and the values of the raw data.

**Comment by meyerch** [comment]
ok, thanks for the clarification
