### ISSUE TITLE
GetFeature info box goes out of frame

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#137]
The GetFeature info box can be unpinned and dragged around the page. 
However, there is no limits as to where it cannot be dragged, meanin that it can go out of frame, as you can see from the screenshot. 

THe issue is that, once out of frame, it is not possible to drag it back in because the 'drag click' only works in the upper part of the box (the blank space that says 'Feature info'). I cannot drag it from any other sides.

So can you solve this, either by: 
- making it impossible for the box to go out of the frame
- making possible to drag the box from any of its sides and not just from the top.

Thank you

![getfeature_outofframe.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef918e258782bd9afbba7cab48e49b2f4035722401e1673295f127b54778154d555ca948090b40f9fddf7df7b33e75dc5c0beed1695f75c33b13bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8d483e18031d88fc5f30a28b06.PNG)

**Comment by afabiani** [comment]
@meyerch this is very strange, I am currently not able to reproduce it on my browser

![image](https://user-images.githubusercontent.com/1278021/40417297-b88958b6-5e7f-11e8-80b8-f784a3c04a4a.png)

![image](https://user-images.githubusercontent.com/1278021/40417358-da189370-5e7f-11e8-9e81-c4fdb7934730.png)

Can you maybe try to cleanup your browser cache and try again?

If it still happens, can you try to describe me the actions you did? And also if this is happening with every layer?

**Comment by meyerch** [comment]
hi @afabiani and @giohappy , 

Giovanni is coorect, this is my issue. THanks for rephrasing it more clearly than I did.

**Comment by meyerch** [comment]
@afabiani 
For this one, I disagree. 
I want to keep the possibility to pin/unpin the FeatureInfo box and to move it around the page, as it is pretty useful when opening several FeatureInfo boxes and comparing data of different elements of a layer. 

So please reactivate his possibility. 

It is not a priority compared to other tasks, so for now you can leave it aside until the others are done . thanks
