### ISSUE TITLE
Incorrect zoom when opening a layer

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#138]
I noticed an issue with the display of some layers when opening some of them. 
Basically, some are more zoomed that what they are supposed to be. This results in information (points/polygons) being out of the viewer frame, whereas before, the entire extent of the layer was displayed within the viewer frame. 

A few examples: 
- http://ihp-wins-dev.geo-solutions.it/layers/geonode:coastal_aquifers_mediterranean_1356
It opens like this: 
![display_zoom_layers6.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec9d89338e82b0b0f3b04ca962fc95304335607f46ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1ef3724e289884b3719001d8ffb5d3cb2d4.PNG)
But should be like this:
![display_zoom_layers6.1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec9d89338e82b0b0f3b04ca962fc95304335607f4af2693cc7f33ab0487e021b4d44be44510e10f8fc8d7df0e739728f0a0bedd26d5b74c73817aeaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4d391a0c1f8cf85a37a6985985.PNG)

- http://ihp-wins-dev.geo-solutions.it/layers/geonode:indicator_data_improved_water_sustai_cities12 
Opens like this:
![display_zoom_layers.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec9d89338e82b0b0f3b04ca962fc95304335606b48e13b628ae92dbc56395b4d5a47fd155c5a40aaafd82ea4b36a708a5f0be9d16c5a72c42f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e58c8b463918071f89fc5827ed.PNG)
But the correct extent is this one:
![display_zoom_layers2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec9d89338e82b0b0f3b04ca962fc95304335607b46ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1ef3724e289884b3719031b81f65835b2d4.PNG)

- http://ihp-wins-dev.geo-solutions.it/layers/geonode:Depth_to_Groundwater_Africa1_test3
Same, with  parts of the raster are out of the frame
![display_zoom_layers3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec9d89338e82b0b0f3b04ca962fc95304335607a46ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1ef3724e289884b3719031180ff5837b2d4.PNG)

- http://ihp-wins-dev.geo-solutions.it/layers/geonode:sdg6_1_1ts_africa_final345
![display_zoom_layers4.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec9d89338e82b0b0f3b04ca962fc95304335607d46ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1ef3724e289884b3719021a89ff5e35b2d4.PNG)

Incidentally, other layers are correctly displayed. For instance: 
- http://ihp-wins-dev.geo-solutions.it/layers/geonode:paratf_male
-http://ihp-wins-dev.geo-solutions.it/layers/geonode:awali_test2315
- http://ihp-wins-dev.geo-solutions.it/layers/geonode:river_basins_dinaricalps

Can you fix this so that the set zoom level when opening a layer allows to display the entire extent of the layer? 
It is how it works for now on the PROD instance, and how it has been before on the DEV. 

Thank you

**Comment by afabiani** [comment]
@meyerch should be fixed now, can you please double check? Please clean up your browser cache or at least reload the page by using CTRL+F5

**Comment by meyerch** [comment]
Hi @afabiani , 

Perfect, thank you.
