### ISSUE TITLE
[Remote Services] Allow registered users to add Remote Layers

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#139]
Registered users can:

1. Add a new Remote Service
2. Add Layers from available Remote Services
3. Edit metadata and remove resources from available Remote Services

Registered users cannot:

1. Delete a Remote Service not belonging to them
2. Modify the metadata of a Remote Service not belonging to them

**Comment by afabiani** [comment]
@meyerch I have deployed on DEV an update to the Remote Services security and management, as stated on the issue above.

As a registered users, it is possible now to access the Remote Services menu

![image](https://user-images.githubusercontent.com/1278021/40610654-954cc692-6273-11e8-870e-6321edfb30b9.png)

It is possible to add a new Remote Service and/or fetch resources from existing Remote Services.

Once the Layer has been created, it's security rules are the same of a standard Layer. The user must edit its metadata, permissions, category and group. A Manager can then "approve" it and an Admin can eventually "publish" it.

**Comment by meyerch** [comment]
Ok, I will check it today. Thanks

**Comment by meyerch** [comment]
thanks
