### ISSUE TITLE
Final check on published Layers

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#14]
"UNESCO-GeoNode-Refactor-2017-Timeline" 'PHASE I'!N11

I changed my email address to my private one (we thought that maybe UNESCO system is filtering notifications email as spamming) and it works! However, for some reasons I received an email saying that "a layer has been updated" when it was actually uploaded, and I received this email 4 times (I received the 4 exact same notifications at the exact same time). 
This leads me to the following question: now that I am advised when a layer is pending approval, how do I do to make it public on WINS once I have approved it? 

Other questions: Are all super users able to receive notifications regarding the upload of a new layer/doc that is pending approval? Or is it linked to an other type of status (somewhere in the system, it says that Alessio and I are the ones allowed to be notified when new layers/doc need approval?)
      All users have access to a notification box where they can choose which item they want to be notified of. Are they only notified of things related to their own layers/maps/docs? For example, when the notification field "a rating was given to a layer" is ticked, is the user only notified when one of his layers/docs/maps is rated? 
     We tested the notifications with a simple user account (gabin.archambault) and a non-unesco email address. He uploaded a layer, that I (chloe.meyer) rated while youssef.filali-meeknassi added a comment. Although all of Gabin's notifications are ticked in the box, he did not recceive any emails advising him that his layer had been rated/commented. Is it normal? On my side, I receieved all the  notifications related to these tests we runed, stating that a layer had been rated/updloaded/commented on/etc.

**Comment by afabiani** [comment]
Yes, it is normal. Internal messages are not related to email. Notifications via email are managed differently from internal messaging system.

**Comment by meyerch** [comment]
accepted
