### ISSUE TITLE
Deleting the 'Time Series' tab

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#140]
Since TimeSeries layers are stored in the "Layers" tab with the other layers, the "TimeSeries" tab in the header is no longer necessary. 
Please delete it. Thank you

**Comment by meyerch** [comment]
![timeserei_tab.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc9d97269186bb8ae08057a55fb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b9884bc5e03d22e18b8f4e3c0c48.PNG)

**Comment by afabiani** [comment]
@meyerch done (on DEV)

**Comment by meyerch** [comment]
ok
