### ISSUE TITLE
New item appeared in the metadata

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#142]
I noticed that there is a new line in the metadata under each item on WINS, called " Licence":
![metadata_new.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5918e228682bd8ed6b146b31fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba821824584b3be8d49c9ee3525e0898c4a2c53.PNG)
(http://ihp-wins-dev.geo-solutions.it/layers/mrms_p24h)

This seems to be recent as the line was not previously embedded the metadata:
![metadata_old.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5918e228682bd8ed6b04fa01fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3be8d49c9ee3526e28f8b4f2c53.PNG)
(http://ihp-wins-dev.geo-solutions.it/layers/geonode:paratf_male)

Indeed, we removed the possibility to indicate a licence in the Wizard tool and Advance edit tool as we don't need it. But the line still shows up under each item.  
Please remove the it.

**Comment by afabiani** [comment]
@meyerch done. There's now a more complex setting in GeoNode to handle this which was not yet configured on the new instance.
Now should be good.

**Comment by meyerch** [comment]
perfect, thank you
