### ISSUE TITLE
PROD - Contributor unable to invite users

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#144]
Dear both, 

I came accross some issues today that I did not notice after you deployed the new version on Prod. 
The first one is that contributors cannot invite users to join the platform: when clicking "invite users" they end up on an "error" page.  (Incidentally, admins do not encounter any issue when trying to invite users).

Please fix this as contributors should be able to invite users.

![inviteusers.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e19a8c2a9686bc9cecad50e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513b820814e80b5bc8f4ec0ed352cef8f8b5d73.PNG)

![inviteusers2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e19a8c2a9686bc9cecad50f61fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bf8a49c2e83b25ee898e4f2c53.PNG)

**Comment by giohappy** [comment]
hi @meyerch we will verify it next days. From a rapid anaysis it seems that a custom control was defined to avoid users from inviting new users. Wasn't it asked from you?

**Comment by meyerch** [comment]
hi @giohappy, 
Thanks for the respone. 
No, it was not. It is the opposite, we asked 'enhancements' (200 email addresses at a time, re-work on the invitation text, etc.) on this to allow contributors to smoothly invite other users.  

Looking forward to have it fixed.

**Comment by giohappy** [comment]
ok, sorry about that @meyerch then.  I will ask @afabiani to verify then.

**Comment by afabiani** [comment]
@meyerch this should be fixed now.

**Comment by meyerch** [comment]
Indeed. THank you
