### ISSUE TITLE
PROD - Contributors able to link their layers/maps/documents to any groups

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#146]
New problem spotted: 

When editting the metadata, a contributor is able to link his layer/codument/map to any groups in the metadata, even the groups which he is not a member of.

Here, najet.guefradj is only member of group "Theme 6: Water education". But she still sees all the other groups in the drop-down menu, and can link her layer to a group she is not a member of. 
I did the test with several other basic contributors, and each can link his item to any groups on WINS.

![group.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692c1e5cdf9ad4cae58f3806b1c65267005a77f25d1e52ebe172954095f4eaf415c5f45f9ff8b39baa47e21d40854b088270a36d43703adb1881eba02ba2782498cb0be8a48c9fa70.JPG)

The correct behavior is: 
A contributor who is a member of groups A, B, and C, should be able to link his item only to group A, B and C (the other groups should not be shown in the drop-down menu).

**Comment by giohappy** [comment]
yes @meyerch I confirm it's the normal behaviour, as you can see in the following image from a demo instance:

![image](https://user-images.githubusercontent.com/571129/42446324-1cc5d708-8376-11e8-9650-5099d9109448.png)

I will close this ticket.

**Comment by giohappy** [comment]
@meyerch the Groups are public? In that case I confirm that a user can view those groups even if they're not explicitely members.

**Comment by meyerch** [comment]
Hi @giohappy , 

All these groups are Public on invitation.
 
As previsouly requested (task #15), the groups showing up in the 'Group' field of the metadata should only be the ones that the contributor is a member of (whether they are 'private' or 'public on invitation') +  the 'public' (regular 'public' not 'public on invitation') ones.

**Comment by giohappy** [comment]
dear @meyerch we have fixed this on GeoNode and the fix has been applied both on test and production. 
I'll wait for your feedback before closing this issue.

**Comment by meyerch** [comment]
Accepted.
