### ISSUE TITLE
PROD - missing tab under a group's activity feed

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#147]
I realise that the "document" tab is missing in the Activity feed of a group. 

FOr instance, on http://ihp-wins.unesco.org/groups/group/IHP-Theme6-Water-education/activity/, we have the tab for layers, for maps, even for comments, but not for documents. 

![activity-feed.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e9978e2a948abd96a4b946a159b2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b9894cc8e83c26e0828e4e3e0c48.PNG)

Is it normal?

**Comment by giohappy** [comment]
yes @meyerch I confirm it's the normal behaviour, as you can see in the following image from a demo instance:

![image](https://user-images.githubusercontent.com/571129/42446324-1cc5d708-8376-11e8-9650-5099d9109448.png)

I will close this ticket.
