### ISSUE TITLE
Issues with VM (read-only filesystem)

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#148]
An error on the VM was reported from the IT services.
Let's see what happens/happened...

---------------------------------------------------------------------
We had some problem with the file system of some VM  . all files systems were in "READ ONLY" mode.
![image](https://user-images.githubusercontent.com/571129/44864621-654aea80-ac80-11e8-9757-e1941116986d.png)

we remark that the job bellow has no limit time.
![image](https://user-images.githubusercontent.com/571129/44864614-60863680-ac80-11e8-8631-f4f3fb6e2ae9.png)

I had to make a reset of the VM.

FSCK had repaired all inodes.

Perhaps this comment shoud be sent to the consultants for advice.
----------------------------------------------------------------------------

**Comment by afabiani** [comment]
@giohappy @meyerch I have checked the VM and everything seems to be fine. The temporary issue with the FileSystem seems to have not impacted at all the instances.

**Comment by meyerch** [comment]
Thanks for the swift feedback, @afabiani
