### ISSUE TITLE
Lock the keywords list so that users cannot add new keywords but have to choose in a set list.

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#16]
"UNESCO-GeoNode-Refactor-2017-Timeline" PHASE I![N:15]

However, we noticed that the keywords are not retrieved in alphabetical order by the system when editing metadata. That is to say, when I edit metadata and enter the letter "e" for example, the system retrieves all keywords that contain an "e", and not only those that start with an "e" (see screenshot in N52). Can you change this so that the keywords retrieved are those starting with the letter(s) entered? For now, there is still this issue.

**Comment by meyerch** [comment]
From what I see on the platform, this is no longer an issue. Keywords are correctly retrieved, in alphabetical order.

**Comment by meyerch** [comment]
accepted
