### ISSUE TITLE
Extend Search to additional fields

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#169]
Currently search is only performed aganst the resources title field. It should be extended to include the following fields:

- abstract
- purpose

This task affects:

- autocomplete API
- search templates / JS scripts

which provide the "backend" logic behind the header Search box and the sidebar TEXT search box.

![image](https://user-images.githubusercontent.com/571129/75141228-cece7c80-56f0-11ea-889e-abf04570e171.png)

**Comment by petrus7** [comment]
This require big refactor. Right now i don't have enough information how to approach

**Comment by giohappy** [comment]
Our discussions on the misleading behaviour of autcomplete with multiple fields, I'm in favour of limiting autocomplete to titles only (as it is know) while perform search on the additional fields.

Refactoring will be eventually scheduled in the future if we have resources left from the other tasks.

**Comment by petrus7** [comment]
This is waiting for other PR to be merged in upstream to avoid ughly history
