### ISSUE TITLE
Extend the publishing workflow to submit edit / delete actions to admin approval 

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#170]
Currently a owner can edit / delete its own resources without the approval from an administraor / group manager.
The purpose of this task is to extend the approval process to any action done by the owner after a resource has been accepted and published (publishing workflow).

**Comment by petrus7** [comment]
@giohappy 
The description is not clear. The goal of this task is: each action on resource requires admin/manager approval. Right?  

Where are those actions? Is this about this button?
![image](https://user-images.githubusercontent.com/44587161/77090314-400b0200-6a07-11ea-8785-d976cabe42f5.png)

**Comment by petrus7** [comment]
This is completely unclear. I got familiar with _Group based advanced data workflow_ section of the doc. Here is start of the discussion for the task. we also should schedule a call. Result of my experiments (i was working with documents):

1) user creates a resource
-resource is not visible outside of the group
- resource requires approval
2) manager approves resource
- resource is not visible outside of the group
- resource  has to be published
3) administrator publishes resource
- resource is accessible according to its permissions (i was testing with any)

Q1) I assume this two step publish flow wont change. right? 

4) user edits (published) resource
- resource is no longer published and not visible, it requires approval and publish steps

Q2) Is it desired behavior? Do we want to keep unchanged resource for users, then when change is published again it will replace old one?

Q3) How about delete? When the owner deletes the resource what is supposed to happen?
Do we keep resource until manager and admin approve deletion?
 
Right now we dont have views for that process. Delete is done automatically after owner requests it. Resource disappear. W need a view: "Request removal" and notifications for manager and admin.  We also need view for managers to approve removal 

Q5) How many actions do we have? 
Right now i can see **delete** and **edit** for documents, in addition, layer has some more options
![image](https://user-images.githubusercontent.com/44587161/77448288-e3398e00-6df0-11ea-8ddf-a1165465a14e.png)
3 for **styles** and 2 for "**layer**"

Q6) Are all those actions affected by this task? 

Q7) If we decide to keep two versions of the resource "published/unbublised" how to manage their displaying

**Comment by giohappy** [comment]
@petrus7 here you have a description of the activity, which simplifies a lot the task and clarifies all you r questions.

### Requirements
When a resource (layer, document, map) is in "published" state, i.e. it has been accepted and published by admins, any "edit" action is hidden to any user (except admins) including the resource owner.

The owner (and only him) will have a new button "Unlock editing". Clicking the button a form will be shown to the user to submit a request to make the resource editable again.
The form will contain a (required) textarea where the user will have to explain the purpose of the request. 
After submission the request will be stored and a notification will be sent to the admin.

The admin will have the option to read the list of grants requests (or go straight to a request through the received notification) and "grant" editing. Grantin actually translates to setting the state of the resource to "pending approval". This action triggers an email notification to the resource owner to inform him that the resource is editable.
The owner will be able to edit the resource until the admin doesn't approve the resource again. 

**NOTE**: I will ask UNESCO tro provide the exact sentences and email bodies (in english and french) to be used. For the moment use simple english sentences as translation placeholders.

**Comment by giohappy** [comment]
UNESCO accepted the proposal for the management of the messaging between the owner and the admins / group managers.

1. when the owner clicks the "editing grant" button, a message is sent to the admins inbox (inside GeoNode). This automatically triggers the sending of an email to the admin, since this has been implemented in this same batch of developments
2. the admin will be able to "accept" the request by changing the approval / is published settings for the sepcific resource
3. He will also be able to reply the user through the Message system to notify him that the request was approved

so @petrus7 everything should be clear now. Go ahead.

**Comment by giohappy** [comment]
Connected to https://github.com/GeoNode/geonode/issues/5990
