### ISSUE TITLE
Include document thumbnail creation inside metadata wizard + zoom/pan/crop widget

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#171]
Extend the document metadata wizard with thumbnail editing.
The new metadata wizard thumbnail edit widget might POST to the same endpoint currently used to upload the document thumbnail.

Something like [Cropper.js](https://fengyuanchen.github.io/cropperjs/) might should be adobted for the new document metadata thumbnal edit widget, to permit the user to pan, zoom and crop the thumbnail image before its upload.

Absolute dimensions are not statically defined for the finel thumbnail DIV element (they have relative values defined by the responsive bootstrap layout) but we can set a fixed ratio of 4:3 and a final dimension of 400:300 px which will work fine even for mobile layout

The positioning of the widget should be similar to the one available for the layer/map metadata wizard.

![image](https://user-images.githubusercontent.com/571129/75146732-f70fa880-56fb-11ea-8deb-223117080636.png)

**Comment by petrus7** [comment]
Solution proposal
![image](https://user-images.githubusercontent.com/44587161/75359821-39301a00-58b5-11ea-8fdb-099c17201dc7.png)

Widget will consist of two parts. 
 - First is image placeholder (designed also as target place for the image) and upload button. 
 - Second is a big popup with workspace area. In that area Cropperjs workspace will be created (green rectangle)

The whole js code will be provided in **<head>** section with others scripts. It will provide a globally available class of the widget. Widget will be placed in the HTML as a **<script>** tag where the constructor of the be called. Constructor will take a **<div>** element as parameter. That element will be the starting point for rendering the widget. Similar approach is used by Cropper itself.

When the user clicks **upload button** open dialog will be displayed, after picking a file **popup** with **cropperjs** will be rendered. User can modify the image. When it is done user may click **Save button**. The image in “crop area” will be sent to image placeholder and **popup** is destroyed.  

The idea is to write only _css_ and _js_ code. The whole _html_ will be rendered by myself. the more mature library i can use the easier it will be react/angular. in Contrary, i can try to render html with _jQuery_

**Comment by giohappy** [comment]
Some comments by points:

1. The image placeholder should behave the same as for the layer wizard. Initially a single "Edit" button is shown and when the placeholder image is changed the two buttons "Save" and "Cancel" are show. In case Save is hit ir will POST to the metadata thumbnail endpoint, otherwise if the user clicks "Cancel" the original thumbnail is shown.

![image](https://user-images.githubusercontent.com/571129/75361246-4cdc8000-58b7-11ea-962b-7877b473cbc0.png)
![image](https://user-images.githubusercontent.com/571129/75361262-5665e800-58b7-11ea-9ec4-73ff2fa25861.png)

2. I wouldn't include React now, just for this component. It would require the configuration of the webpack config, the build, etc. And I wouldn't use Angular, since the one bundled with GeoNode is old (1.7.x) and we aim at replacing it. I think that jQuery is enough for this component.

3. It would be great if we could implement this as a js object (which will handle the DOM management, the interaction with cropper, etc. internally) with a simple API. We could bundle this js inside the GeoNode scripts bundle and make it reusable in the future.  This is a plus and should only be considered if we have time left.

**Comment by petrus7** [comment]
@giohappy sure, task is clear

**Comment by petrus7** [comment]
@giohappy 
One last thought about react, there is the repository:
https://github.com/facebook/create-react-app

Which is a boilerplate and wrapper for webpack (no configuration is required its easy to use). it provides a component template, i feel react and that quickstart repo is exactly what we need: small, light, reusable component to eaisly write htmlless widgets . I believe it will make development  faster

**Comment by giohappy** [comment]
I know, we use React everywhere and our frontend team is made of React experts.
The problem here is that there are already several parties that have pending proposals to integrate React in GeoNode. I support this but in that case we should discuss it with the community, and I fear it won't be a quick process. 
Moreover we have Angular... I'm not sure of the side effects of mixing React with Angular 1.x, both of them acting on the same pages. Do you have experience with such a time bomb?

**Comment by petrus7** [comment]
No i have never mix angular and react. Maybe they can coexist, Angular is creating its own event loop, components lifecycle and so on, maybe it won't interact with react as long as they interact with the same DOM element. But im not expert here.

Ok ill proceed with jquery, for the moment

**Comment by petrus7** [comment]
@giohappy @afabiani 

Can you tell me how to download and upload the document thumbnail to the server? 
i would appreciate requests urls and parameters required

**Comment by giohappy** [comment]
@petrus7 I guess you can obtain them looking at the other document thumbnail edit options in GeoNode:

![image](https://user-images.githubusercontent.com/571129/75659559-76582b80-5c6a-11ea-998a-396acad94fa7.png)

**Comment by petrus7** [comment]
During my work:  
I encountered some problems using thumbnail upload endpoint:
`/base/{id}/thumbnail_upload`
I tried to use existing flow which is accessible here:
![image](https://user-images.githubusercontent.com/44587161/75865085-43956b00-5e03-11ea-9c01-86e8402d2053.png)
After uploading image server is throwing exception:

`Traceback (most recent call last):
  File "/home/petrus/geo_solutions/geonode/geonode/base/models.py", line 1554, in thumbnail_url
    os.rename(upload_path, _upload_path)
FileNotFoundError: [Errno 2] No such file or directory`
https://github.com/GeoNode/geonode/blob/c5b291cae13f30523765cecc18d0185622550501/geonode/base/models.py#L1561

Despite that if i reload page thumbnail is created correctly. Is this relevant? 

Another issue is:
To finish task i have to prefetch current document thumbnail. I found the endpoint:
api/documents/{id} 
Which is returning thumbnail_url. That thumbnail seems to be not correct. It is different than uploaded one. I noticed that the thumbnail returned in mentioned endpoint is the same as "autogenerated" thumbnail

![image](https://user-images.githubusercontent.com/44587161/75867263-a1778200-5e06-11ea-9304-dc7741362e7b.png)
 
Above screenshot is taken from upload thumbnail view. The autogenerated thumbnail and the thumbnail in the /api/documents seems to be something called  `curatedthumbnail`

The question is how to get current thumbnail in simple api call (i need that image to dynamically load through ajax requests)

**Comment by giohappy** [comment]
@petrus7 point by point:

### Error with thumbnail_upload
Are you getting this error only with a custom upload or even from the thumbnail_upload form?
In latter case I can't reproduce it

### Curated thumbnail URL
I confirm that `api/documents/{id}` returns the auto-generated email instead of the curated thumbnail (the one you upload). I've [opened an issue for this](https://github.com/GeoNode/geonode/issues/5804).
By the way you don't need to call the API to retrieve the right URL. IN the context of the wizard template you have the `resource` object. From it you can retrieve the right thumbnail with `{{ resource.curatedthumbnail.thumbnail_url }}`.
Of course this needs a check, in case a thumbnail was never uloaded. In that case only the auto-generated is available, and you can get it from `{{ resource.thumbnail_url }}`.
You can look at the [thumbnail_upload.html](https://github.com/GeoNode/geonode/blob/master/geonode/base/templates/base/thumbnail_upload.html) template to view how it works.

### Remove "Set" option
The Set button, which links to the thumb_upload page, is the old way of uploading thumbanils for docs. Now that we have the Upload option the Set option should be removed.
I will create a task for this.

**Comment by giohappy** [comment]
closed in https://github.com/GeoNode/geonode/pull/5818
