### ISSUE TITLE
Add email notification to inform user of new messages

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#172]
An email notification will be added to inform users about new messages directed to him.

The email subject and body templates should be configurable. 
The subject for IHP will be: "You have received a message on WINS".

The email notification text will include a link to the user's inbox, where he can view the message.

**Comment by petrus7** [comment]
Should be email sending async process? 

In my opinion this should be incorporated into user-messages module

**Comment by giohappy** [comment]
As agreed the tasks for this issue are:

- implement a "senhd_mail" (celery task) method inside PeopleProfile model
- make the account adapter use this method instead of the [current local one](https://github.com/GeoNode/geonode/blob/master/geonode/people/adapters.py#L154)
- implement a callback method inside user_messages module to send an email on message sent (only if user has an email defined)
- make the callback setup configurable through a new "USER_MESSAGES_SEND_EMAIL" variable wichh will be False by default

This must be done on the upstream repos (geonode and geonode-user-messages)

An additional task on dev_py3 branch is:

- make [this method ](https://github.com/geosolutions-it/unesco-ihp/blob/dev_py3/ihp/people/models.py#L170)use the new mail sending method instead of the one from local adapter
