### ISSUE TITLE
Integrate fix to print dialog

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#182]
#156 is fixed.
Now we have to:

- create a temporary 1.4.x branch on geonode-mapstore-client and backport the fix
- update the geonode-mapstore-client inside the geonode UNESCO branch to point to the 1.4.x branch instead of 1.4.8
- backport the [fix to the layer and map detail templates](https://github.com/GeoNode/geonode/pull/5770) (yet to be merged) to the unesco branch

NOTE: this is a temporary solution for the release of UNESCO with geonode 2.10.2.

**Comment by afabiani** [comment]
done
