### ISSUE TITLE
Configure text for email notifying user of new comments

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#184]
**UPDATE**: they ask how much it would take to implement a configuration option to make the notifications of new comments on resources to be sent only to the resource owner

### Current/Old “new comment” notification email:
**Subject**:
`A comment has been posted for a layer`

**Text**:
```
You have received the following notice from ihp-wins.unesco.org:

A comment has been posted for the layer Types of UNESCO City Networks in the Megacities
by the user Chloe.Meyer
You can visit the layer&#39;s detail page here: http://ihp-
wins.unesco.org/layers/geonode:City_UNESCO_Category0

To change how you receive notifications, please go to http://ihp-wins.unesco.org
```

### New “new comment” notification email:
**Subject**:
`IHP-WINS: A new comment has been posted on a layer`

**Text**:
```
Dear contributor,
The user Chloe.Meyer has posted a new comment on the layer “Types of UNESCO City
Networks in the Megacities”.
You can visit the layer&#39;s page here: http://ihp-
wins.unesco.org/layers/geonode:City_UNESCO_Category0
If you want to change how you receive notifications, please go to http://ihp-
wins.unesco.org/notifications/settings/
The IHP-WINS Team
```

copied from [this document](https://drive.google.com/open?id=1O8JkBQVUMP4ZprLiQIUOxKMBlSJ4A1t0) provided by Chloe

**Comment by petrus7** [comment]
@giohappy task is relatively easy. i would say 1 day of work.  
I have question, where current emails are sent?  I cannot find the place

Comment is sent through **geonode-dialogos**, which has **post_comment**, there is the signal: **commented**. But nothing is subscribing that signal

**Comment by giohappy** [comment]
I would use an approach similar to what we've done for messages. We could add a signal handler inside the notifications module (along with the message handlers) and send the email from there.

**Comment by petrus7** [comment]
This waits for https://github.com/GeoNode/geonode/pull/5915 to be merged

**Comment by petrus7** [comment]
@giohappy can you ask UNESCO about French version of the email?

**Comment by petrus7** [comment]
@giohappy here is email template
https://github.com/geosolutions-it/unesco-ihp/pull/209
and here is logic:
https://github.com/petrus7/geonode/pull/9

**Comment by petrus7** [comment]
TODO: Include admins in comment notification
