### ISSUE TITLE
Change default user avatar

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#189]
The following one will be used

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/141c7051-3426-46df-88d1-d9111e038885)

**Comment by petrus7** [comment]
Port to geonode

**Comment by petrus7** [comment]
@giohappy its here 
https://github.com/geosolutions-it/unesco-ihp/commit/abe85f6c70d6bf12a4aea361d2d62793bf7ef6e6
