### ISSUE TITLE
Change document-layer relation. For now, we can only mention one layer in the "Resource using this document" box. We want to be able to mention several layers related to one document.

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#19]
"UNESCO-GeoNode-Refactor-2017-Timeline" PHASE I![N:19]

Comment: Additionally, once a layer is selected in the “Links to” box, it is impossible to update the metadata and to save the document-layer relation. The updating process starts running but never ends, in both the Wizard and the Advanced edit. PROBLEM: now we can save the metadata but there is still an issue. For a document with completely filled and saved metadata: everytime we go back in the Wizard, the metadata are said to be incompletely filled, until we add again a layer/map in the "links to" box. See the screenshot at the end of the table

I still have the same issue as before: whenever I want to "update" metadata in the Wizard after having selected a document-layer relation, the updating process starts but never seems to end. However, if I click "Done!" directly, the metadata seem to be saved within the second, and I get back to the document page (I tried with this document : http://ihp-wins-dev.geo-solutions.it/documents/512). 
There is another issue. For the aforementionned doc, I saved a document-layer relation with this layer: http://ihp-wins-dev.geo-solutions.it/layers/geonode:arab_states_region. Once I save the doc's metadata (including this doc-layer relation), I am brought back to the document's page, where it says that "This document is not related to any maps or layers". When I open again the Wizard, the "Link to" box is empty  as well as the "keywords" box: none of the 2 have been saved.

**Comment by afabiani** [comment]
This error happened when in the Keywords selectbox a tag appear more than once. This should not happen, usually, but it may happen if there some error on the metadata xml.

A fix on GeoNode has been pushed in order to overcome such kind of exceptional cases.

**Comment by meyerch** [comment]
ACCEPTED
