### ISSUE TITLE
Display issue with the Temporal extent inside metadata wizard

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#191]
Original comment:

> In the Wizard (when editing metadata), there is a display issue with the Temporal extent (see picture). I think you can remove the text that reads “*Field declared mandatory by the metadata systems” as it is already in the ‘Mandatory tab”. Maybe it will solve the display issue?

If the fields are mandatory they should be marked in red, like the others.

![image](https://user-images.githubusercontent.com/571129/76308245-a76bd800-62ca-11ea-8f06-b0b79b27a3f5.png)

**Comment by petrus7** [comment]
@giohappy neither for document nor for layer fields from section number 2 of metadata are mandator (even if they are marked mandatory in the frontend, update is fine when they are not set) 

Im going simply remove this prompt for date fields. If this requires more changes in the future we should refactor code anyway
