### ISSUE TITLE
Increase items per page for Resources and Contributors

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#192]
Original message:

> Only 5 layers/maps/documents/groups are now displayed on each page (see: http://ihp-wins.unesco.org/layers/?limit=5&offset=0). Please make sure that at 25 items are displayed on each page, to avoid having to go to the next page too often.

Currently they're configured to 5. Increase it to 25.

**Comment by petrus7** [comment]
@giohappy this is not an issue. Is about set proper env var: CLIENT_RESULTS_LIMIT

**Comment by giohappy** [comment]
please set it in ihp.settings.py, both on dev and dev_py3
