### ISSUE TITLE
Allow signin with email

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#213]
Request from UNESCO:

"Allow users to sign in with their username OR their email address. For now, it is only possible to sign with the username."

We need to verify all the implications of this change:

- unique case insensitive emails (cannot create multiple users with same email)
- any side effect during the authentication / autheorization process

**Comment by abulojoshua1** [comment]
After taking a look at this issue, I got thoughts of setting alluth's [ACCOUNT_AUTHENTICATION_METHOD](https://django-allauth.readthedocs.io/en/latest/configuration.html) settings key to `username_email` to allow login using both email and username. Any thoughts @afabiani?

**Comment by giohappy** [comment]
ok @abulojoshua1 seems to be fine.
Please proceed adding this custom configuration inside ihp_settings and verify that:

1 - user must enter email during registration (it should already be in place inside the registration form)
2 - check that user can actually login both with email and username (received by email after registration approval)
