### ISSUE TITLE
Implement Download Survery

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#218]
A "survey" Django module will be created.
Two models will be implemented inside the module to provide:

- The surveys model
- a (singleton) Configuration module where the admin will configure:
   - the expiration time to show the survey form again to the user (managed through a browser cookie)
   - enable/disable the survey

For the singleton model we can do something similar to the [GN global Configuration singleton](https://github.com/GeoNode/geonode/blob/185816630c9f4ad5cf41cc90246971c55256d2a4/geonode/base/models.py#L1594)

The document [download links](https://github.com/geosolutions-it/unesco-ihp/blob/86830aa872d3b8eecf882d54c17425da48fc264e/ihp/templates/documents/document_detail.html#L105) and[ layers download links](https://github.com/geosolutions-it/unesco-ihp/blob/master/ihp/templates/layers/layer_detail.html#L430) will be replaced with a link to a new custom /download Django view.

The original download link will be passed inside  "download_url" GET parameter, and the original (document or layer) detail page URL will be passed inside  "next" GET paramater.

Example

`ihp.org/download?download_url=https://master.demo.geonode.org/download/2708?access_token=EPCNTL6x29h8wWqRkMHJE91unOtH3Q&next=https://master.demo.geonode.org/layers/geonode_data:geonode:building_Merge`

The download view will present a page with the survey form. After filling the form a hitting submit, the page will render a message like:

"Thanks for submitting....
Go back to the <a href="{next url}">resource page</a>"

and the download starts (download_url url)

 

The survey must be active for all kind of downloadable resources: layer, document, map

**Comment by abulojoshua1** [comment]
@giohappy, following yesterday's discussion about this issue, I'll stick to the work plan as described above and I estimate this issue at 5.

**Comment by giohappy** [comment]
After some more thoughts the following can be implemented since, actually, the same system can be used to cover both anonymous and authenticated users:

1) for authenticated users only the purpose textarea is shown, while for anonymous users we also show the other fields
2) we could make a single survey model, where all the fields are defined + a FK to the user. For anonymous users the fields are filled from the survey form and the FK is null; for authenticated users the fields values are copied from the user itself and the FK points to the user

in the next phase we will extend the survey app to create tokens and send emails to anoymous users IF the "download request" feature is on

**Comment by abulojoshua1** [comment]
> After some more thoughts the following can be implemented since, actually, the same system can be used to cover both anonymous and authenticated users:
> 
> 1. for authenticated users only the purpose textarea is shown, while for anonymous users we also show the other fields
> 2. we could make a single survey model, where all the fields are defined + a FK to the user. For anonymous users the fields are filled from the survey form and the FK is null; for authenticated users the fields values are copied from the user itself and the FK points to the user
> 
> in the next phase we will extend the survey app to create tokens and send emails to anoymous users IF the "download request" feature is on

@giohappy, I've made some new changes addressing the above, kindly take a look whenever possible.
