### ISSUE TITLE
Unexpected behavior of resource created under different RESOURCE_PUBLISHING setting

### ISSUE THREAD

**Issue by petrus7** [geosolutions-it/unesco-ihp#235]
I noticed something unexpected when resources are created under different value of RESOURCE_PUBLISHING.

Resource created with RESOURCE_PUBLISHING=False is not exposing **Edit** button for group managers
![image.png](https://images.zenhubusercontent.com/5cdaa0ea7c26f80232635039/16672dfc-c35b-4c66-8ce0-a08abc71585d)

**Edit** button is not shown when RESOURCE_PUBLISHING is set to True and server restarted
Button is visible in case RESOURCE_PUBLISHING was True during its creation

This causes the manager is not able to unpublish all resources he manages. Is this desired behaviour?  

Environment: 
branch: dev_py3

**Comment by petrus7** [comment]
Update. This occurs when user publish resource by itself but ONLY when group was not previously set. 

Here are two cases:
1) user creates document
2) user fills metadata: set group
3) save
4) user publish it
5) save

Manager is fine he can access his edit button

Second case:
1) user creates doc
2) user fills metadata: group AND mark as published
3) save

Manager is not able to hit his edit button

**Comment by afabiani** [comment]
Yes it is a desired behavior, see https://docs.geonode.org/en/master/basic/settings/index.html#resource-publishing

However the documents template has few wrong checks. Will create a PR for that.

**Comment by giohappy** [comment]
@afabiani what @petrus7 is saying is that this mechanism has different behaviours in case the owner sets the resource to "published" together with the group, or if it sets the group and then it sets the resource to publish.
This is an inconsistency.

**Comment by afabiani** [comment]
@giohappy @petrus7 PR in progress [here](https://github.com/GeoNode/geonode/pull/5994)

**Comment by afabiani** [comment]
@giohappy @petrus7 this is fixed by https://github.com/GeoNode/geonode/pull/5994

**Comment by petrus7** [comment]
I confirm, bug is fixed
