### ISSUE TITLE
Add French translations to the web-site

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#24]
Update POs files in order to apply correct French translations to the whole page.

**Comment by meyerch** [comment]
As you know, we requested you to change the word "Owner" for 'Responsible" (in the metadata and in the search menu), which is done perfectly. 

Please do the same  change in the French version: replace  "Propriétaire" for "Responsable".
THanks

**Comment by meyerch** [comment]
ACCEPTED
