### ISSUE TITLE
Extent filter map not showing

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#244]
![image](https://user-images.githubusercontent.com/1278021/78700478-af3c8d80-7905-11ea-9213-36c3de75b215.png)

**Comment by giohappy** [comment]
We couldn't replicate this @afabiani . The extent filter appears and seems to working fine.

![image](https://user-images.githubusercontent.com/571129/79550236-59e84500-8098-11ea-8e39-4f55b5b5e222.png)

**Comment by afabiani** [comment]
Yeps, it is now showing, but the filter throws exceptions

![image](https://user-images.githubusercontent.com/1278021/79551026-6b7e1c80-8099-11ea-9f4b-9869cae0f36a.png)

**Comment by giohappy** [comment]
I don't know if you dev is up to date (including geonode deps) but locally I can't see any exception

![image](https://user-images.githubusercontent.com/571129/79553161-58b91700-809c-11ea-8b65-7cfc57d63660.png)
