### ISSUE TITLE
Documents details Edit button should not be visible if I have no rights to edit

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#251]
Apparently only for documents, if I go to the details page logged int ad a user with no rights to edit, the "Edit Document" button is shown. However if I click on it the dialog is empty.

The button should not be visible at all in this case, like for the Layers and Maps.

**Comment by giohappy** [comment]
@afabiani is it caused by the template override? Have you checked that this doesn't happen on geonode master?

**Comment by giohappy** [comment]
it only happens for UNESCO

![image](https://user-images.githubusercontent.com/571129/78784900-73a5d000-79a6-11ea-994a-55c0d7c43138.png)

**Comment by afabiani** [comment]
@giohappy fixed by https://github.com/geosolutions-it/unesco-ihp/pull/254
