### ISSUE TITLE
Review unesco email templates 

### ISSUE THREAD

**Issue by petrus7** [geosolutions-it/unesco-ihp#253]
Last weeks many new email templates were created on upstream, ensure we provide unesco ones for them

**Comment by giohappy** [comment]
please @petrus7 list them here with checkboxes

**Comment by petrus7** [comment]
@giohappy Here is list of recent email templates(not marked still require overriding):

[] new message notification email #198 
[] new message notification email french #198 
[] new message notification subject #198 
[] new message notification subject  french #198 

[] request change email #170
[] request change subject  #170
[] request change email french #170
[] request change subject  french #170

[] new comment email #184 
[] new comment email subject  #184
[] new comment email french #184
[] new comment email subject french #184

**Comment by giohappy** [comment]
@petrus7 so on this we need to ask UNESCO the franech trnaslations to be applied, right?

**Comment by petrus7** [comment]
@giohappy yes indeed
