### ISSUE TITLE
About page template with TOC

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#26]
Create an "About us" template with TOC following instructions by UNESCO.

Provide the possibility of somehow editing text from admin, or at least partners logos and links.

**Comment by afabiani** [comment]
As an admin everything can be edited from "http://ihp-wins-dev.geo-solutions.it/admin/content/"

About Us
========
Can be added/edited from http://ihp-wins-dev.geo-solutions.it/admin/content/aboutuspagecontent/

Only the newest one will be displayed. Content must contain HTML formatted text.

![2017-09-11 12_50_04-Change about us page content _ Django site admin.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2b8ee03f50fcfc1797977276427ab2a7e82e668be4074141b4f0bef51180e13a9e9da74f8f2692ece4c64fda5370e2a916201efe1c64aaf50ee7dd21197aaaeca0e9fb26876a399855d3b17544c8dfa5963f6c84eca5da04be14e55a0133766e074246055d64f2b78343a7fe1a99d448d9761a3b0112a56cde2e6fd1610a07fd1c01b3c.png)

Partners
=======
From http://ihp-wins-dev.geo-solutions.it/admin/content/partnericon/ it is possible to add/edit/delete partners hrefs and icons. Those must be 164x164px. The list will be ordered in alphabetical order based on partner name field

![2017-09-11 12_48_22-Change partner icon _ Django site admin.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2b8ee03f50fcfc0717975216427ab2a7e82e668af436915010a0cbc180b001aec96995ffce76227d54c48b495384f25926048f2aa9e0dff43e57ade1cc1a4b69849c9b96921e28fd9196f1b071ddfff5d36a09d4bc95df049f35147e6426837b92b6f3612d60c7f3e69662caaf9df53868766adb8192851cef1a9.png)

Contact Us
=========
The same of  About Us

FAQs
====
Each FAQ must belong to a FAQ-Topic. Those can be added/edited from http://ihp-wins-dev.geo-solutions.it/admin/content/faqtopic/

They will be listed ordered by "order" field.

Questions can be added/edited from  http://ihp-wins-dev.geo-solutions.it/admin/content/faqquestion/

Those are ordered by ID inside its Topic, and a question must belong to a Topic.

In order to display it on the page, once inserted go back to the Topic and highlight it on the multi-select box. Then save.

![2017-09-11 12_54_45-Change faq topic _ Django site admin.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2b8ee03f50fcfc17d7973266427ab2a7e82e668b9436a411b000ef51248305488a3d875f1e92c33d3185efd8039022d982f0dbef8c040e554e964994597b3b5db18c4ed3973b1da8a4d3b4805188aff5935a19c4dca4aea59a31c0bf04c6b3aac23746e4d861c74266a6226aefddd51848562a7b2183d1b.png)

**Comment by meyerch** [comment]
ACCEPTED
