### ISSUE TITLE
New custom field "Group(s) you want to join" is not showing under django admin

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#263]
The new field (implemented in https://github.com/geosolutions-it/unesco-ihp/issues/166) isn't available under django-admin. 

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/fcffe1b1-af40-428e-a918-232d9b468fd4)

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/5f3632a8-5b73-40e1-a980-c3a521cac6d3)

**Comment by abulojoshua1** [comment]
@giohappy, the fix for this looks straight forward to me, I estimate it at 1.
