### ISSUE TITLE
Two clicks are required to delete a message

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#270]
Something wrong happens when the Delete button is clicked on a message.
Please check it also happens on GeoNode itself.

![click_twice_to_delete.gif](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/63b2b5e5-198c-4138-9a7c-fda27aeaff26)

**Comment by petrus7** [comment]
its broken on upstream too

**Comment by giohappy** [comment]
closing in favour of https://github.com/geosolutions-it/geonode/issues/471
