### ISSUE TITLE
Some actions make the "select groups to join" field show the group number instead of the name

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#271]
Generally it happens when the registration page is refreshed for whatever reason (e.g. missing required field).
In that case the group name in the "groups to join" field is replaced with a number (I guess the group or groupprofile id), nad it keeps showing the number even if I remove the group and add it again.

![groups_to_join_issue.gif](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/a2881c8c-2cc9-4603-b39d-ea79816d95b9)

**Comment by abulojoshua1** [comment]
@giohappy, I'll start working on this issue as soon as I get done with what I am working on currently, most likely next week Monday :)
