### ISSUE TITLE
"Dcouments amd ""Explore Documents" still use the default labels for ensglish, instead of "Library"

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#272]
According to issue https://github.com/geosolutions-it/unesco-ihp/issues/163 the "Documents" tab (and I'd say the "Explore documents" label) must be translated to "Library" / "Explore library".

The msgids seem ok but the GeoNode default values are still shown.

 - "Documents": https://github.com/geosolutions-it/unesco-ihp/blob/dev/ihp/locale/en/LC_MESSAGES/django.po#L120
 - "Explore Documents": https://github.com/geosolutions-it/unesco-ihp/blob/dev/ihp/locale/en/LC_MESSAGES/django.po#L1409

Maybe the messages need to be compiled again?

![image](https://user-images.githubusercontent.com/571129/80387086-7fe7c380-88a8-11ea-8ee1-d6d833271b5d.png)

**Comment by petrus7** [comment]
@giohappy you reverted this here:
https://github.com/geosolutions-it/unesco-ihp/commit/9302786cc696e645ed1f8bde6f12db53c8b2edd4

**Comment by giohappy** [comment]
I reverted because I wanted to use the original "Documents" msgid instead of creating a new "Library" label in template.
By the way I see that these would probably affect also the message "XXX Documents found", so actually we need to adopt your initial solution.

Please revert my revert :)

**Comment by petrus7** [comment]
Everything looks fine on my local configuration

**Comment by giohappy** [comment]
to be investigated on dev server
