### ISSUE TITLE
Fix notification body for resource comments

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#276]
The notification process for a new comment works. However, the text of the notification does not look good (see below). Please make sure that the html signs (`<body>` ; `<br>` ; `</p>` ; etc.) are not showing. PLEASE NOTE THAT THIS APPLIES TO ALL NOTIFICATION MESSAGES, WHICH AT THE MOMENT ARE ALL SHOWING THOSE HTML SIGNS. 

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/de957173-c918-4a70-a65e-a875b1f24727)

**Comment by petrus7** [comment]
@giohappy are you sure this was working? Please look here:
https://github.com/pinax/pinax-notifications/blob/254560473ba3e942123c68dabbf21184fab2624f/pinax/notifications/backends/email.py#L44

To send HTML email you have to provide **html_message** parameter for the **send_message**
https://docs.djangoproject.com/en/3.0/topics/email/#send-mail

which pinax is not doing

**Comment by giohappy** [comment]
@petrus7 you're right, pinax doesn't seem to support html contents. 
The message sent on comments have been added by us, so in this case we must change it to send a plain text message.

**Comment by giohappy** [comment]
Forget my previous comment.

@afabiani please check how we sent HTML messages before and let's restore it for the current version.

**Comment by afabiani** [comment]
@giohappy Done.

Fixed through https://github.com/geosolutions-it/unesco-ihp/commit/47674a473f68417056bb29ce76966b76edd48b8f
