### ISSUE TITLE
Search users in Create message mix results

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#278]
"The new interface is ok. However, there is an issue is with the search tool (when searching for recipients, whether being contributors or groups): the system does not retrieve correctly the names searched for."

![image](https://user-images.githubusercontent.com/571129/81693852-d5070600-9460-11ea-9917-fc90b5f8820b.png)

**Comment by petrus7** [comment]
@giohappy its about widget rendering, its too slow, requests are fine for each time

**Comment by giohappy** [comment]
@petrus7 please check if we can easily introduce a debounce to that widget, to delay the request after a certain amount of time since user stopped keytyping.

Search and returned values could be enhanced. We should search usernames, first names and last names, and return a unique result with preference for firstname.lastname, in case they're available for a user. 
This will require some more work so let's keep this on hold for the moment.

**Comment by giohappy** [comment]
After reviewing this with UNESCO it seems that results from typeahead overlap and are applied out of order.
Please @petrus7 check the order of requests and responses and how they affect the presentation of results.

**Comment by petrus7** [comment]
@giohappy yes this is cuz of request execution times and the order
![image](https://user-images.githubusercontent.com/44587161/81832116-6b5d2980-953e-11ea-9f11-6e71dfe3abbd.png)
