### ISSUE TITLE
With “Layer published” notification activated notifications for new layers created are sent

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#281]
"When the “Layer published” notification is activated, the user receives an email when a layer is created (i.e. uploaded) and when a layer is published. Please correct so that when a layer is created, the user only receives a notification if he has activated the “Layer created” notification."

First let's scheck if we can reproduce the reported behaviour. In case it's confirmed it must be fixed.

**Comment by petrus7** [comment]
@giohappy blocked until we have a decision on 284

**Comment by giohappy** [comment]
As discussed the real question here is why emails are sent even if "Layer created" notification is turned off.
Please @petrus7 invetigate. 

I don't care for the moment about the doubts on the positioning of the notification trigger.

**Comment by petrus7** [comment]
@giohappy enabling/disabling notification in the user panel works fine.

**Comment by giohappy** [comment]
Did you test this with "Layer Published" turned on? They say that the notification is sent if "Layer Published" is on and "Layer created" is off.
Please test it on their dev instance too.

**Comment by petrus7** [comment]
@giohappy when you disable notification it is not sent and this works. confirmed locally and on unesco dev server. What is the decision about sending emails?

**Comment by giohappy** [comment]
I will tell them that we weren't abel to replicate the problem then...
If it works as expected I don't want to change anything about mail sending right now.

**Comment by petrus7** [comment]
@giohappy 
we already hit the issue i described yesterday. there is some code that performs saves and each save generate email(I don't know exactly why and where but that's is fact). If the user has all notifications for layer enabled, upload a new layer generates 5 emails!

**Comment by giohappy** [comment]
> @giohappy when you disable notification it is not sent and this works

but you kept "Layer Published" on, right?

> If the user has all notifications for layer enabled, upload of new layer generates 5 emails!

ok, so I would just add a check inside the current code to send the notification only if it's a new resource, and discard changes after that. But I don't want to move the code elsewhere for the moment

**Comment by petrus7** [comment]
> but you kept "Layer Published" on, right?

If you have this on email is sent otherwise its not

**Comment by giohappy** [comment]
so @petrus7 you didn't read my previous comments accurately :)
This is exactly the issue reported by UNESCO. They expect (as me) that the email for "layer created" is never sent if it's turned off, independently from the other notifications settings.
