### ISSUE TITLE
Remove "Ne results found" from search autocomplete

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#282]
No results found was ok until Search autocomplete was consistent with actual search filters, but now that we have extended the search to "description" and "purpose" fields it happens that autocomplete doesn't show anything but if the search is performed we get results.

The idea is to remove the "No results found" message from all the search boxes, and I would do it upstream.
What's your opinion @afabiani ?

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/3aefd0a1-cd9a-483e-8c01-9076f46b6c66)

**Comment by afabiani** [comment]
Let's remove the "No results found" feedback.

**Comment by giohappy** [comment]
@petrus7 why is this in Review state? Review should only be used for PRs and related issues
