### ISSUE TITLE
Hide / Remove "Registered memebers" group

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#286]
@afabiani we need to 

- [ ] verify that [AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME](https://github.com/GeoNode/geonode/blob/master/geonode/groups/conf/settings.py#L31)
- [ ] we can safely remove the "Registered Members" group

Actually I would make GeoNode avoid creating that default group if AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME is off.

**Comment by afabiani** [comment]
@giohappy done.
Dev server updated.
Settings updated: https://github.com/geosolutions-it/unesco-ihp/commit/76bdf02306716cd21c4ece5bf048efd6defb595e

**Comment by giohappy** [comment]
ok but what will happen the next time we configure the server? Will the Registered Memebers be created even if the setting is off?

**Comment by afabiani** [comment]
Nope, the gruop is created only if the option is True

https://github.com/GeoNode/geonode/blob/master/geonode/groups/apps.py#L35-L37
