### ISSUE TITLE
Move triggering of notificationson on the side of the sender

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#287]
The current way of sending notifications inside post save signals causes a weak control over their sending, which in many cases translatea into double (or more) sendings of the same notification, or their trigger even in cases where they are miningless to the receiver.

Following from the suggestion of @petrus7, we want to move away notifications from signals (at least for those related to resources) and place them where an action really wants to trigger them (e.g. CRUD views, import workflow, etc).

We should strive to adopt the DRY principle, and reduce the burden on the sender.
My proposal is to overload the save method ResourceBase (as a polymorphic class), with an additional "notify" parameter, which will be set to False by default.

Please @afabiani assign and estimate before proceeding.

**Comment by afabiani** [comment]
Done through https://github.com/GeoNode/geonode/pull/6100/
