### ISSUE TITLE
Mandatory tabs are marked red even if all fields are filled

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#288]
![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/bcd42afc-36e1-4322-8723-ff836ab90cc0)

**Comment by afabiani** [comment]
Done by updating GeoNode

![image](https://user-images.githubusercontent.com/1278021/82303091-c49fdf80-99ba-11ea-91ac-927e09887481.png)

**Comment by afabiani** [comment]
some layers are still missing DOI on the second tab... taking a look

**Comment by afabiani** [comment]
done, DOI was set on another window.

**Comment by giohappy** [comment]
We need to fix the mising handler on time widgets, inside the second tab, otherwise the tab remains red until you don't tuch another (optional) field or click Update.

![image](https://user-images.githubusercontent.com/571129/82318158-ae504e80-99cf-11ea-99c8-275b9ef0e8c6.png)

**Comment by afabiani** [comment]
Done

![image](https://user-images.githubusercontent.com/1278021/82320351-66332b00-99d3-11ea-9023-9a4ed06b503f.png)

**Comment by giohappy** [comment]
closed through https://github.com/GeoNode/geonode/commit/109ad2ca141876cc9912a538ccb851b81a84d471
