### ISSUE TITLE
Filter by extent broken

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#298]
Filtering by extent is broken for IHP WINS (it works on GeoNode master demo).
@afabiani supposes it's because of a misalignment with the UNESCO templates.

Examples: http://ihp-wins.unesco.org/api/layers/?extent=-113.40953536066958,-15.409608905637441,-75.96812911066955,34.77917311878991&limit=25&offset=0

**Comment by petrus7** [comment]
@giohappy this is not happening to me locally. Is that server up to date? Is underlying geonode up to date?

**Comment by giohappy** [comment]
ok, let's see if an upgrade of GeoNode fixes this.
