### ISSUE TITLE
Error creating thumbnail during document upload

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#299]
The backend throws an error during the document upload procedure when the thumbnail must be saved to disk.
@afabiani did a quick try changing the folder permissions but it doesn't solve the problem. As a temporary workaround a "try catch" expressions has been inlined on the server (to be removed when it's fixed!).

You can test this doing an upload on http://ihp-wins-dev.unesco.org/. It will create the document but not the thumbnail, but without the try / catch the upload will fail leaving an inconsistent state (document listed but can't be opened).

**Comment by petrus7** [comment]
Which thumbnail do you mean? 
This:
![image](https://user-images.githubusercontent.com/44587161/96114746-4ce0cd00-0ee6-11eb-8e58-8bcd47949e85.png)
or this:
![image](https://user-images.githubusercontent.com/44587161/96114783-58cc8f00-0ee6-11eb-9f84-461a741c6520.png)

Both are working for me locally. Can you give me access to the server and point me to where the logs from uwsgi lives? Or at least please provide traceback for this error

**Comment by giohappy** [comment]
it happens on their prod and dev envs. Don't worry about this issue for the moment. I will move it to the inbox...

**Comment by petrus7** [comment]
i dont know neither their dev nor prod. can I get the address, username, path where the app is deployed, path to logs. maybe its a mater of stale GeoNode(today i had to set up env for unesco again so I'm running the newest GeoNode)

**Comment by giohappy** [comment]
ok, let's see if an upgrade of GeoNode fixes this.
