### ISSUE TITLE
WP6 [B4] - Users

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#30]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Set up the messagery so that users can send a message to several other users, and to an entire group. For now, users can only contact one person at a time.

**Comment by afabiani** [comment]
Send to Group still to be implemented

**Comment by afabiani** [comment]
TODO: Improve "geonode-user-accounts" module and enable GeoNode to send messages to all members of a Group.

WARNING: Groups to be listed must be only:
- The ones I'm member of
- The PUBLIC ones (no PUBLIC-INVITE neither PRIVATE)

**Comment by afabiani** [comment]
Done

**Comment by ricardogsilva** [comment]
@afabiani perhaps we can close the issue?

**Comment by meyerch** [comment]
Thank you. This is ACCEPTED. 

However, I have spotted 2 issues, for which I am going to open new tasks.
