### ISSUE TITLE
Download survey does not work for maps

### ISSUE THREAD

**Issue by abulojoshua1** [geosolutions-it/unesco-ihp#303]
Download survey does not apply for downloads in the maps detail page.

### How to reproduce
- Make sure download survey is enabled in the admin page
- Navigate to a map detail page
- Download a thumbnail/Remote Thumbnail
- The download survey is not triggered

**Comment by giohappy** [comment]
download survey is only needed for the original datasets, not for maps. The same applies to layers: you can download an image of it, without hitting the download survey.
