### ISSUE TITLE
Install new instance of IHP

### ISSUE THREAD

**Issue by ndhuygelaere** [geosolutions-it/unesco-ihp#305]
Hi, i'm trying to install IHP on a new server for a project fund by unesco.

After a long installation process i get this error: 

ERROR: Could not find a version that satisfies the requirement pytest==6.1.1 (from GeoNode->-r requirements.txt (line 1)) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.9.0, 2.9.1, 2.9.2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, 3.9.1, 3.9.2, 3.9.3, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8, 4.6.9, 4.6.10, 4.6.11)
ERROR: No matching distribution found for pytest==6.1.1 (from GeoNode->-r requirements.txt (line 1))
WARNING: You are using pip version 20.1; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip install --upgrade --no-cache-dir --src /usr/src -r requirements.txt' returned a non-zero code: 1

Do you have any solution ?

I have also seen IHP use python 2.7 and this version have already reached the end of its life. Do you have already try to install IHP with python 3.6 or 3.8 ? and with last version of geonode ?

Thanks

**Comment by giohappy** [comment]
@ndhuygelaere we're not providing free support on this custom project. If you need professional support please write to info@geo-solutions.it.
