### ISSUE TITLE
Integrate upgrades to charts

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#306]
This will come for free when [this will be merged](https://github.com/geosolutions-it/MapStore2/issues/6044) since we're targeting geonode master.

**Comment by simboss** [comment]
@allyoucanmap @giohappy I can't seem to be able to configure a chart in dev.
Is this still open ?

**Comment by giohappy** [comment]
> @allyoucanmap @giohappy I can't seem to be able to configure a chart in dev.
Is this still open ?

@simboss what do you mean? Charts are supported inside maps.
And they also some support some curious effect :)

![bouncingchart](https://user-images.githubusercontent.com/571129/107037547-869e5200-67bb-11eb-8491-c749578cb056.gif)

**Comment by giohappy** [comment]
@simboss if you refer to charts for layers I remind you htat we decided to do not implement them,

**Comment by allyoucanmap** [comment]
@giohappy @simboss in addition the charts are only available in the `/edit` page for maps
