### ISSUE TITLE
Flicker of preview panel on mouse over

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#313]
![sfarfallio mouse](https://user-images.githubusercontent.com/571129/101831322-0ac6b700-3b36-11eb-978e-9db70419ba11.gif)

**Comment by allyoucanmap** [comment]
I was able to replicate but this is a corner case. I was able to avoid this by forcing the overflow-y always to scroll

![image](https://user-images.githubusercontent.com/19175505/101895529-f0c5bc80-3ba7-11eb-8450-90fc12ee9012.png)
