### ISSUE TITLE
Styling of preview panel

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#316]
I would change the positioning of the elements inside the preview page:

 - reduce title font from 1.875rem to 1.2rem
 - reduce abstract font from 1.12rem to 0.9rem
 - move author and pubication date below the title
 - remove the time from publication. The day is enough
 - decrease the author and date block to 0.9em
 - justify abstract text
 - decrease the categories field to 0.9em
 - loghten the category name. Black bold makes this field the most relevant within the panel. If we don't have semibold weight we can use a dark grey in place of full black

![image](https://user-images.githubusercontent.com/571129/101833846-d05f1900-3b39-11eb-87c8-1ae33c6076e0.png)

**Comment by allyoucanmap** [comment]
> - loghten the category name. Black bold makes this field the most relevant within the panel. If we don't have semibold weight we can use a dark grey in place of full black

could we make it clickable instead? Click will apply a filter similar to author and in this way the style is lighter and less relevant in the panel

![image](https://user-images.githubusercontent.com/19175505/101895529-f0c5bc80-3ba7-11eb-8450-90fc12ee9012.png)
