### ISSUE TITLE
Implement preview for layers in the new homepage

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/unesco-ihp#325]
Layer preview is still missing, we need to implement it before closing this work package.

**Comment by giohappy** [comment]
As agreed a temporary solution will we implemented for the current homepage. A new one will be needed when the architecture for the new client will be in place.

**Comment by giohappy** [comment]
As agreed the client will implement the layer_embed template that will be provided by GeoNode. 
MapStore will obtain the layer configs from the ms2_config context prepared by GeoNode (mapstore adapter) then it will perform all the additional logic to take full control of the maps plugins and page presentation.
