### ISSUE TITLE
Implement layer embed view in GeoNode

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#326]
For #325 we agreed to let the client take full control of a layer embed template. In order to obtain it we need to:

 - implement a "layer_embed" url and view in GeoNode. The layer will prepare the `config` context according to the layername GET parameter
 - create a layer_embed.html with only the `{% get_layer_embed %}` tag

The template context will automatically have the ms2_config and so the client will be able to complete the implementation of the page.

@afabiani we need this on master branch so that it will be available inside the unesco-ihp dev branch.

**Comment by afabiani** [comment]
@giohappy @allyoucanmap here the commit on GeoNode master https://github.com/GeoNode/geonode/commit/38959bdfad4dc33360437c5bdad697dda06e222b

Should I create a template on mapstore-client too? Or @allyoucanmap will take care of this?

**Comment by giohappy** [comment]
> @giohappy @allyoucanmap here the commit on GeoNode master GeoNode/geonode@38959bd

@afabiani aren't the url and view required?

> Should I create a template on mapstore-client too? Or @allyoucanmap will take care of this?

I suppose @allyoucanmap can do it by hiumself. It should be a matter of uncommenting and changing [this line](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/hooksets.py#L130) to `return 'geonode-mapstore-client/layer_embed.html'
`

**Comment by afabiani** [comment]
@giohappy yeps, sorry. Added here 
https://github.com/GeoNode/geonode/commit/1f8c053e5bce63ed7dc5cca4be061e3f14e6a750

**Comment by afabiani** [comment]
@giohappy @allyoucanmap once the `geonode-mapstore-client/layer_embed.html` is ready on mapstore-client I will start the release process for both the adapter and the client
