### ISSUE TITLE
Upgrade dev server 

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#328]
with [the latest improvements](https://github.com/geosolutions-it/unesco-ihp/pull/327) to the home page and the client

**Comment by afabiani** [comment]
@giohappy done, to summarize:

- Updated the code (both GeoNode and MapStore client)
- Enabled fully async mode (it was a sort of hybrid setup before), which means:
    - Installed rabbitmq-server
    - Installed Memcached service
    - Updated celery worker startup command (and supervisor accordingly)
    - Updated the env variables
- Refreshed statics and migrations (there were some sort of misaligned with the Thesauri for some reason)
