### ISSUE TITLE
Run full test of dev server

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#329]
@ElenaGallo time to test http://ihp-wins-dev.unesco.org/.

Please also test the functionalities on the new home page, in particular:

 - the previews in the sidebar, when you click on a card
 - the filters, that you can set clicking on the filter icon inside the search bar

**Comment by ElenaGallo** [comment]
@giohappy tests done, [here](https://docs.google.com/spreadsheets/d/1v0cfKI-QnzOULftrbDzJRdaSEaAAkvFFfxIZBfaqmWw/edit#gid=376642658) the spreadsheet. We have some failed tests in the filters on the homepage

**Comment by giohappy** [comment]
@allyoucanmap can you please give a look to the failed tests?

**Comment by allyoucanmap** [comment]
@ElenaGallo @giohappy I added some notes in the spreadsheet here a summary:
- most recent order: I'm able to reproduce it only after login (need to investigate but seems a 500 internal error see below *)
- geostory in resource types list: those values are provided by the backend at this endpoint http://ihp-wins-dev.unesco.org/api/v2/resources/resource_types
- filter by owner: I tried to apply a filter with the owner but I did not get errors

(*) The error messages show that there is a 500 status and usually in geonode there is an html page with specific information. 
In this case I'm getting:

http://ihp-wins-dev.unesco.org/api/v2/resources?sort[]=-date&page=1&page_size=20
![image](https://user-images.githubusercontent.com/19175505/108985826-c60cdf80-7691-11eb-8bcb-5ccca8bc0c8f.png)
![image](https://user-images.githubusercontent.com/19175505/108986096-11bf8900-7692-11eb-9221-fee7a8d6f438.png)

**Comment by giohappy** [comment]
> most recent order: I'm able to reproduce it only after login (need to investigate but seems a 500 internal error see below *)

I will open an issue for this

> geostory in resource types list: those values are provided by the backend at this endpoint http://ihp-wins-dev.unesco.org/api/v2/resources/resource_types

can you please try again? I can see geostory listed inside the dropdown

![image](https://user-images.githubusercontent.com/571129/108987024-1a648f00-7693-11eb-8862-9bb0b39f182f.png)


> filter by owner: I tried to apply a filter with the owner but I did not get errors

@ElenaGallo probably you were misguided by the delay before the filtered resources appear. Is it?

**Comment by ElenaGallo** [comment]
> @ElenaGallo can you please try again? I can see geostory listed inside the dropdown
@giohappy @allyoucanmap My question here was: why is geostory listed in the dropdown menu if geostory service is not available in this instance

> @ElenaGallo probably you were misguided by the delay before the filtered resources appear. Is it?
@giohappy @allyoucanmap I rewrote the steps for reproducing the issue for [lines 5 and 6](https://docs.google.com/spreadsheets/d/1v0cfKI-QnzOULftrbDzJRdaSEaAAkvFFfxIZBfaqmWw/edit#gid=376642658&range=5:6)

**Comment by giohappy** [comment]
Ok, it's clear now. I've opened https://github.com/geosolutions-it/unesco-ihp/issues/334 and https://github.com/geosolutions-it/unesco-ihp/issues/333

**Comment by ElenaGallo** [comment]
@giohappy Now all the tests on the spreadsheet are passed.
