### ISSUE TITLE
User button / avatar is not visible

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#330]
1. Sign In
2. The user button is not shown

![image](https://user-images.githubusercontent.com/571129/108987364-7cbd8f80-7693-11eb-9af2-b4283bb338fa.png)

**Comment by allyoucanmap** [comment]
after a quick investigation I noticed that the request for user data returns forbidden even if the same user is logged in.
The homepage does following request:
- `http://ihp-wins-dev.unesco.org/api/o/v4/userinfo`
- `http://ihp-wins-dev.unesco.org/api/v2/users/{sub}` sub values in userinfo request

**Comment by giohappy** [comment]
closing in favor of this https://github.com/geosolutions-it/unesco-ihp/issues/332
