### ISSUE TITLE
User info endpoint returns 403 (forbidden) to autheticated users

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#332]
1. Login as admin
2. Open [this URL](http://ihp-wins-dev.unesco.org/api/v2/users/1701)

![image](https://user-images.githubusercontent.com/571129/108990110-b5ab3380-7696-11eb-9c0f-74835a8151d5.png)

**Comment by afabiani** [comment]
@giohappy PR available [here](https://github.com/GeoNode/geonode/pull/6992)
