### ISSUE TITLE
Should we complete the geostory support for the UNESCO template?

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#334]
Since we're using a custom template the "geostory" things weren't added to it, since they've never been requested.

@simboss in case we want to promote them at UNESCO I think we should communicate the addition, since they're quite strict about their template.
Otherwise we have to disable them.

**Comment by simboss** [comment]
this was not requested so we I would not enable it just yet.

**Comment by giohappy** [comment]
Ok, issue created here https://github.com/geosolutions-it/unesco-ihp/issues/336
