### ISSUE TITLE
user menu for non-admin users is showing unwanted links

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#335]
I suppose "Anouncements" is the only one that needs to be dropped, but please double check @allyoucanmap 

![image](https://user-images.githubusercontent.com/571129/108998256-f0b26480-76a0-11eb-8e78-057d8658acd0.png)

**Comment by allyoucanmap** [comment]
> I suppose "Anouncements" is the only one that needs to be dropped, but please double check @allyoucanmap

@giohappy going to remove also Remote Services

![image](https://user-images.githubusercontent.com/19175505/109032099-a1caf600-76c5-11eb-9fa3-e164e262cf6d.png)
![image](https://user-images.githubusercontent.com/19175505/109032180-b3140280-76c5-11eb-9e29-dc28e3a3706f.png)
