### ISSUE TITLE
Issue with creating new styles

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/unesco-ihp#344]
As per row 79 of the [tests spreadsheet](https://docs.google.com/spreadsheets/d/1ZTosUUjBRPJ_K4Z_9lJWD8sLi8xiZfnkVIqHTQAFxO4/edit#gid=376642658) we have some issues with styles encoding.
We shall investigate and propose a fix.

**Comment by afabiani** [comment]
No errors apparently on GeoNode code base, it turns out that there are invalid characters inside the custom UNESCO template

```
(geonode3) geosolutions@ihp-wins-dev:~/work/repo/ihp$ grep -axv '.*' ihp/templates/layers/*.*
ihp/templates/layers/layer_style_edit.html:{% block title %}{{ resource.title|default:resource.alternate }} ▒ {{ block.super }}{% endblock %}
(geonode3) geosolutions@ihp-wins-dev:~/work/repo/ihp$
```

**Comment by simboss** [comment]
@afabiani thanks for spotting this.

What is the proposed plan for fixing the issue?

**Comment by afabiani** [comment]
First of all we need to clean up that HTML file and then we will need to pull it on prod server.
There's no need to rebuild anything or restart any service, it is just matter of replacing a file.
Let me know how you think is better to proceed.

**Comment by simboss** [comment]
hiu @afabiani, please go ahead and clean the HTML file then give us instructions to fix this on the server.

I will discuss with @giohappy and @randomorder on best way to apply this.

**Comment by afabiani** [comment]
@simboss @giohappy commit available [here](https://github.com/geosolutions-it/unesco-ihp/commit/a6c27d326f6f74bea72e20de002fc18f1a358f96)

**Comment by randomorder** [comment]
I can ask @lpasquali to patch it along with its review of the instllation @simboss

**Comment by simboss** [comment]
@agpenton let's discuss it afterwards.

**Comment by simboss** [comment]
@afabiani this has been deployed right?

**Comment by afabiani** [comment]
@simboss yes
