### ISSUE TITLE
Upload SLD style issue

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/unesco-ihp#356]
It is not possible uploaded [this style](https://github.com/geosolutions-it/unesco-ihp/files/6477498/a__1503_Elevaciones.zip)

**How to Reproduce**
From [this layer](http://ihp-wins.unesco.org/layers/geonode:a__1503_Elevaciones_3gaZjr6) follow the steps in the gif:

![sld style](https://user-images.githubusercontent.com/56537133/118242984-36abe700-b49e-11eb-80d9-32a65ad64a06.gif)

**Comment by marthamareal** [comment]
@giohappy  The problem seems to be with the file its self. when you open it its not xml, rather it appears corrupt. (Similar error is got trying to update that file on master demo)
But when you upload a valid file, its successful.

**Comment by giohappy** [comment]
@ElenaGallo where does that file come from?

**Comment by giohappy** [comment]
so apparently the user included an invalid style when the layer was uploaded.

@simboss I would consider this investigation closed.

**Comment by simboss** [comment]
@giohappy thx, @ElenaGallo let's fix the dataset.
