### ISSUE TITLE
WP6 [B10] - Layers/Maps/Documents/Groups

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#36]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Fix bug with wrapping. Lines are correctly wrapped in metadata and under some viewers (not the Document viewer), but once in the list (of Layers/Maps/Documents), wrapping disappears and is replaced with a wide space.

**Comment by meyerch** [comment]
Going through the task, I realised that the explanation for this one is not really clear. Sorry about that.
Here is a screenshot of the issue, for a better understanding.
Exemple given for http://ihp-wins-dev.geo-solutions.it/layers/geonode:sdg6_1_1

![line-wrapping1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e49d9426cf94bb8ef9af4aaa5aa1d665043761260ea62864c7b96aea1b7a055b5a4afa17095a46f9af892ba5b638708b590defc3714d36976345f3e5db55ea43a82a994d84bcbd8f4cc8ea392de182884f3a161755.PNG)

For the same layer, when consulting the metadata ("metadata detail"):
![line-wrapping2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e49d9426cf94bb8ef9af4aaa5aa2d665043761260ea62864c7b96aea1b7a055b5a4afa17095a46f9af892ba5b638708b590defc3714d36976345f3e5db55ea43a82a994d85bcbd8f4cc8ea392de083864a3b191755.PNG)

**Comment by meyerch** [comment]
It also happens when editing the metadata:
![wrapping-metadata3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ff869b33928aa788a4b246b05cf4953d4774316546b3397f8fe62bab0021435a561ff8455d5b12aaa88c29a3e03c70895c0fedd0685976d42103eee9dc4be05ce36ade0d97bcae8b44cae93825ef898a4d3f1d031f88fb4f78.PNG)

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
accepted
