### ISSUE TITLE
WP6 [B11] - Layers/Maps/Docs

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#37]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Fix bug that occurs when replacing layer. When editing layers, we have the option of replacing it (for update for exemple), but it does not work. For now, if we want to update a layer, we have to delete the old one and retake the process of uploading a new layer (filling metadata, etc.). As a result, it takes much more time and all views and comments left are lost.

**Comment by afabiani** [comment]
Fixed.

**Comment by meyerch** [comment]
Perfect, thanks. 

ACCEPTED
