### ISSUE TITLE
WP6 [B12] - Layers/Maps

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#38]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Use UNESCO_GEODATA map as default basemap  in every viewers

**Comment by meyerch** [comment]
No longer relevant : we are perfectly fine with the way it is now, i.e. having the OPENSTREETMAP background as the default basemap in every viewer. 

(this task must have stayed in the GoogleDoc from months ago)
