### ISSUE TITLE
WP6 [B13] - Layers/Maps

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#39]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Add a "no background" in the list of basemap in every viewers

**Comment by afabiani** [comment]
My suggestion is to use geoexplorer instead of leaflet viewer on layer and maps details page, so that they are aligned.

Note: 3D viewer is no longer supported by Google

**Comment by meyerch** [comment]
Accepted
