### ISSUE TITLE
WP6 [B14] - Groups

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#40]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Fix bug that prevent group profile picture to show up on the "Group" page

**Comment by afabiani** [comment]
Should be fixed now. Most of the groups do not have a logo. To test it please update new ones. If a logo is present, it is shown instead of the group name (which is available on mouse hover).

**Comment by meyerch** [comment]
For now, no group profile picture shows up in the list. But the picture appears when consulting the group's profile (see screenshots below)
![group-logo2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692cea580eeb011e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513bb27814e80b6b48e4fc0ea3c27e3898f5d73.PNG)

for http://ihp-wins-dev.geo-solutions.it/groups/group/Admin/ :
![group-logo.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692cea580eeb001e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b22a8a4a85beb8894cc2eb3b2de2829d02.PNG)

**Comment by meyerch** [comment]
what we have in mind is having the picture next to the name and description of the group, when in the groups list:
![group-logo3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692cea580eeb010e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513bb28814e80b6b48e4fc0ea3420e783885d73.PNG)

**Comment by afabiani** [comment]
Ok then. will revert to "In Progress"

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
thanks, 
ACCEPTED
