### ISSUE TITLE
WP6 [B16] - Layers/Maps/Docs

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#42]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Fix bug that occurs with every Layer/Map/Document title on their respective pages and metadata. When the title is long, it is not wrapped on the pages, but cut instead.

**Comment by afabiani** [comment]
Done.
![2017-10-19 12_26_14-Estimated Disability-Adjusted Life Years attributable to water, sanitation and h.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f9c2b8e603f50fcfc67f7976276421b03f7988e23cba463b25061c1ffe18040600b5e4f87ffcf37f34df081b91883b0a64af6840eefb924efb45f879d90ac1e7eed619d0ac6235a0dacb1a7c02155bd8a10471f1dd129706e61abf1945fc012a71a634692612c75a672679622ffaa8db5383d336f5bf122a00c8e3e7fa1212a079dec51b6d71170af47e6de85b10dc228a4c6a5ce2bfc5f817440c1e09c4ebcbd8b8eac97c.png)
![2017-10-19 12_26_33-Estimated Disability-Adjusted Life Years attributable to water, sanitation and h.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f9c2b8e603f50fcfc67f7974206421b03f7988e23cba463b25061c1ffe18040600b5e4f87ffcf37f34df081b91883b0a64af6840eefb924efb45f879d90ac1e7eed619d0ac6235a0dacb1a7c02155bd8a10471f1dd129706e61abf1945fc012a71a634692612c75a672679622ffaa8db5383d336f5bf122a00c8e3e7fa1212a079dec51b6d71170af47e6de85b10dc228a4c6a5ce2bfc5f817440c1e09c4ebcbdfbdedc97c.png)

**Comment by meyerch** [comment]
perfect. Accepted
