### ISSUE TITLE
WP6 [B18] - Metadata

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#44]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Add 2 line wrappings in every metadata.

**Comment by afabiani** [comment]
Should be already fixed with latest layout reviews.

**Comment by meyerch** [comment]
Accepted.
