### ISSUE TITLE
WP6 [B19] - Users

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#45]
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Fix bug in users' profile : overlay of groups' logo and groups'name

**Comment by afabiani** [comment]
Should be fixed now. See also #40

**Comment by meyerch** [comment]
Accepted. Thanks
