### ISSUE TITLE
Emails sent to the user once his/her account is activated

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#55]
Please find below the text for the Welcoming email (received y the user once the account is approved). "XXXXXXXX: is obviously meant to be replaced by the username of the person. See below:

(Subject:) IHP-WINS account approved/Compte IHP-WINS approuvé 

Dear contributor, 

Welcome to the Water Information Network System!

You can now sign in to http://ihp-wins.unesco.org/. Your username is XXXXXXX and your password is the one you chose when registering.

IHP-WINS is an open-access, knowledge-sharing platform on water-related issues at all levels, maintained by UNESCO International Hydrological Programme. Contributors are invited to join and participate to the initiative by sharing data and interacting with the other users.

We hope to see you there!

The IHP-WINS Team

---------------------------------------------------------

Cher contributeur, 

Bienvenue sur le Système de Réseau d’Informations sur l’Eau! 

Vous pouvez désormais vous connecter sur http://ihp-wins.unesco.org/. Votre nom d’utilisateur est XXXXXXX et votre mot de passe est celui que vous avez choisi lors de l’inscription. 

Disponible en accès libre, IHP-WINS est une plateforme de partage d’informations sur l’eau a tous les niveaux, et est maintenue par le Programme Hydrologique International de l’UNESCO. Les contributeurs sont invités à rejoindre la plateforme et à participer à l’initiative en partageant des données et en interagissant avec les autres utilisateurs.  

Nous espérons vous y croiser ! 

L’équipe IHP-WINS

**Comment by meyerch** [comment]
Here is the text for the Notification email, also to be sent once the account is approuved. As for the previous email, “XXXXXX” is to be  replaced with the username. 



(Subject:) IHP-WINS Notifications/Notifications IHP-WINS 

Dear contributor, 

You have received the following notice from http://ihp-wins.unesco.org/. 

Your account (XXXXXX) has been approved and is now active. 

To change how you receive notifications, please go to http://ihp-wins.unesco.org /notifications/settings/.

The IHP-WINS Team

---------------------------------------------------------

Cher contributeur, 

Cette notification vous a été envoyée par http://ihp-wins.unesco.org/. 

Votre compte (XXXXXX) a été approuvé et est désormais actif. 

Pour modifier vos paramètres de notifications, rendez-vous sur http://ihp-wins.unesco.org /notifications/settings/.

L’équipe IHP-WINS

**Comment by afabiani** [comment]
Can you please check?

![image](https://user-images.githubusercontent.com/1278021/31223576-101b3456-a9cb-11e7-9d4e-04f7886bb845.png)


![image](https://user-images.githubusercontent.com/1278021/31223597-20de1f24-a9cb-11e7-9cb8-19ae30b06a08.png)

**Comment by meyerch** [comment]
Perfetct! ACCEPTED
