### ISSUE TITLE
Layers thumbnail

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#56]
There seems to be an issue with the saving and updating of the thumbnail layers. 
Many times, I saved a new thumbnail through the Wizard tool and it looks like it was saved. However, once I returned in the Layers’ list, the thumbnail that is displayed is the ancient one.  

I did those tests a few days ago. Today, i was going through the Layers list on the platform, and realized that all the tumbnails that I saved the last time (but that seemed not to be saved, as explained in the message above) currently appear in the Layers list as I saved them (I purposely zoomed in a lot when editing the thumbnail to check if it was working. See screenshots below of how they are now correclty displayed in the list now). 
So apparently, they have been saved, but did not show up immediately afterwards.

A few minutes ago, I tried again to update a thumbnail (for http://ihp-wins-dev.geo-solutions.it/layers/geonode:hg_units_all_merged_1). Same than last time: in the Wizard tool, it says that it is saved, but once back in the Layers list, the old thumbnail is still on display.

![layer_thumbnail.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e495832690bcbd87fcb241aa5cf9986b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84b1b68b49c0ef3c27e18a894f3b1a010ac4.PNG)

**Comment by afabiani** [comment]
This is an issue of the browser cache. The thumbnails are saved.

**Comment by meyerch** [comment]
perfect, thanks
