### ISSUE TITLE
Overlapping text - French version

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#58]
In the French version, in the 'Edit layer' pop up box, the text systematically expends outside its assigned box. Changes in screen resolution have no visible impact on this. 
See screenshot below.

**Comment by meyerch** [comment]
![Overlap_EditLayer-french.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46c7829f318e82b9b0ccbb4ab071f18d2c546a753b01ad2878c7af6aaf50740b0a0c0abe4b4a5a4dadad8d2ea2e06a218f5e0ebbd16d5c74c23d10a9be800da313f871d51bdaebe5c01982fa3737e683854e3b1e02198afb5c3da89f4ec04abb.PNG)

**Comment by afabiani** [comment]
Changed to

![image](https://user-images.githubusercontent.com/1278021/31191116-6f4fbbec-a93d-11e7-88e3-a4af01799d0c.png)

**Comment by meyerch** [comment]
perfect, thanks. ACCEPTED. 

Before this task is archived,  I just have a question: 
Is there a way for us to directly change the French translation of the website if we notice some errors or poor translations?

**Comment by afabiani** [comment]
Hi yes, there's a opensource program called poedit which allows you to edit message files (I can send them separately). Please let me know if you need them. Let's move the thread on mail.
I will close this for now.
