### ISSUE TITLE
Transparency in the viewer

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#61]
Transparency is no longer working in the viewer.
 
However, once you change the background layer to any other, then tranparency work again (even if I set up the background layer back on OSM)

**Comment by afabiani** [comment]
I'm going to change the GIS client. Let's see how it goes with the new one.

**Comment by afabiani** [comment]
Can you please check the new GIS client and see if it matches your needs?

**Comment by meyerch** [comment]
Now the option to change transparency of the layer has simply disappear form the new viewer..!
Please make sure that we hae the possibility to change transparency in the layer viewer

**Comment by afabiani** [comment]
It is possible either from the map or the style editor. The option present before, did by previous developers, was not stored on the layer/map configuration but just a functionality of the viewer. I can put similar option on the viewer, but it won't be stored permanently. Again, to store it permanently you need to update either the style or the map. I can show you how to do it.

**Comment by meyerch** [comment]
Ok, then I will update style/map. 
Please let me know how to do this. Thanks

**Comment by afabiani** [comment]
![layer_opacity](https://user-images.githubusercontent.com/1278021/31388771-66aa6992-adcf-11e7-9984-ac70a4ec2d54.gif)

**Comment by afabiani** [comment]
![layer_opacity_map](https://user-images.githubusercontent.com/1278021/31389122-61d96f5c-add0-11e7-8d98-19b1aa243c61.gif)

**Comment by meyerch** [comment]
I understand that a logged in contributors can play with transparency this way. 

My problem is that now, users (i.e. anyone who does not have an account on WINS) is no longer able to change the transparency of the layer. It means that  users without account can no longer create maps with some layers that would need transparency to be overlaid.  

I have to discuss with Youssef on this, and I will come back to you with more precision on what we want

**Comment by afabiani** [comment]
Hi, this is possible also as an anonoymous users from the "Create Map" tool exactly in the same way as shown above.

Login is required actually only to "save" the map into the system. 

Question is, do we really wont anyone to save maps on the system? 
We can remove the login check but how we can prevent anonymous people from saving thousands Maps? And how to track them?

Consider also the "public" layers are accessible through external GIS clients like QGIS anyway.

**Comment by meyerch** [comment]
Following the Webex meeting,  we have agreed on leaving the transparency as is. 
I.e. anonymous users can change the transparency of the layers in a map, without interfering with the style on the backend. And those anonymous users cannot save the map, but can style print it. 

So this task is ACCEPTED.
