### ISSUE TITLE
Creation of the Get started page

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#63]
Can you please create the "Get Started" so that we can start editing it?
We would like to be on the same model that the 'About us" page, i.e. a page that links to other page, and that we can edit from the admin interface (change both title and text). 
See screenshot of what we have in mind in terms of number of 'sub-pages'.

**Comment by meyerch** [comment]
![get-started-pages.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef918e6e9197a89dfdba47e94df1932c55653f6b14b1247a80e03cfd183954560e1aa8445c0912adfc8b2ef0b63c738a580becd46b5d66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3d22ef898a4b36190c1e8ced10.PNG)

So the idea is that the "indtroduction"/"Basic user module"/"advance user module" all link to their own page, as the menu on the right shows. 
THen we will populate each page with the text.

**Comment by afabiani** [comment]
You can edit/add documentation pages from

http://ihp-wins-dev.geo-solutions.it/admin/content/documentationpage/

![image](https://user-images.githubusercontent.com/1278021/31550506-da09772a-b031-11e7-8b43-de82729ad9a4.png)

It is possible to add ad many page you want; the important thing is to correctly select the "parent" page

![image](https://user-images.githubusercontent.com/1278021/31550542-024734e8-b032-11e7-99b5-be72e999ce54.png)

![image](https://user-images.githubusercontent.com/1278021/31550557-0efbabc4-b032-11e7-897e-4a9df64232ae.png)

**Comment by meyerch** [comment]
Please make sure that the entire menu (the one displayed on the right here: http://ihp-wins-dev.geo-solutions.it/get-started/1/) is display on every page under the documentation section. 
For now when I click on each one of the sub-item (introduction/basic/advance) I end up with a one-line menu on the right (see screenshot below):
![documentation-page.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec9b99368f86a79be8ab4aab53bd84284122316546b3397f8fe62bab0021435a561ff8455d5b12aaa88c29a3e03c70895c0fedd0685976d42103eee9dc4be05ce36ade0d97bcae8b4bcae93825e0828f4a3b1900118af74f78.PNG)

**Comment by afabiani** [comment]
Done

**Comment by meyerch** [comment]
Accepted
