### ISSUE TITLE
Print preview extent (GeoExplorer map client)

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#64]
This follows issue #60. Since there are still problems, I am creating a dedicated issue for this point.

**Comment by meyerch** [comment]
ORIGINAL MESSAGE: 
There is an issue with the scale in the PrintPreview [in addition to the extent-related problem stated above].
First, the scale of 1:512,000,000 as indicated in the drop-menu is not accessible, and we need it.
Second, there is a mismatch between the zoom through the zoom-bar and zoom through the drop-menu, as explained below.

The PrintPreview opens up with a minimum, said-scale of 1:256,000,000 (1st screenshot)
printpreview1.PNG

If I click 2 times on the zoom bar (on the left on the PrintPreview), I end up with a said-scale of 1:64,000,000 (screenshot)
printpreview2.PNG

However, then if I select scale 1:64,000,000 through the drop menu (bottom of the PrintPreview), I end up with a different zoom (screenshot)
printpreview3.PNG

Then, I select scale 1:128,000,000 through the drop menu again, I end up with the same result as when the PrintPreview opens up with a said scale of 256,000,000 (screenshot below, to be compared with the 1st sreenshot)
printpreview4.PNG

**Comment by meyerch** [comment]
I checked again today, there are still the same problems, i.e. descrepancies between the scale in the drop-menu and scale in the zoom slider
In the drop menu, scales '1:279,540,572' and '1:139,770,286' show the exact same extent. See 2 screenshots below:
![print-preview11.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d96ceb99deca94aa14aa1c56b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84b1b68b49c0e03c21e38e8c4c3f17040ac4.PNG)
![print-preview22.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d96ceb99deca94aa14aa2c66b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84b1b68b49c0e03c21e38e8b493e180c0ac4.PNG)

**Comment by afabiani** [comment]
I will open a separate and specific issue for that, since this is a frontend component of GeoExplorer and will require further investigation on JavaScript.

**Comment by meyerch** [comment]
For the public launch of the platforme, this is the priority. 
THey are other issues linked to the print preview/PDF that ended up being created: 
I am splitting the issues in different messages for easier understanding. See below

**Comment by meyerch** [comment]
1/ The UNESCO-IHP and WINS logo should be embeded in the final PDF (at the same place as they are currently in the viewer). This is not the case for now

**Comment by meyerch** [comment]
2/ When ticking "include legend" on the print preview, the PDF created ahs no legend.
Here I ticked "legend": 
![print-map.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d96cea48ef9fd0fe64de29b234324676b5ee17e2984e77cea167d070e5a4ca917585f47fcfd892aa3b03e62964e49bc8f3900299f7744eeaa880dbe06b0218e4f8cb5bb8b49c1ee3b2ce099c2.PNG)

Thi is the PDF obtained :
![print-pdf.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d96ceb98beffd0fe64de29b234324676b5ee17e2984e77cea167d070e5a4ca917585f47fcfd892aa3b03e62964e49bc8f3900299f7744eeaa880dbe06b0218e4f8cb5bb8b49c6eb3523e299c2.PNG)

**Comment by afabiani** [comment]
@meyerch 

This is actually the outcome of PDFs for Maps.

Still working on some improvements and fixes, but in the meantime can this be good for you? Can you please provide feedabcks?

![2017-11-07 13_35_14-Water points in Central America.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f8c2b9e803f50ecfc77c7976276433a23f7597a338b04b75151c4f17f2512b0a1ab8bbd877b6c76125c80558bcc3714d3484624bf9ebc60db513bf29da1b81b3b8dc1a91ed3f20b18b8f4c3e1a05198cf95f27bc8b099906a214bc141ff1512469f4773e7646911f752c6e6f27adfade5485972d.png)
![2017-11-07 13_36_26-Water points in Central America.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f8c2b9e803f50ecfc77f7975256433a23f7597a338b04b75151c4f17f2512b0a1ab8bbd877b6c76125c80558bcc3714d3484624bf9ebc60db513bf29da1b81b3b8dc1a91ed3f20b18b8f4c3e1a05198cf95f27bc8b099906a214bc141ff1512469f4773e7646911f752c6e6f24abf9d95e86972d.png)

**Comment by meyerch** [comment]
In the pdf outcome, is it possible to have the UNESCO and WINS logos (the ones in the header) within the frame of the map? 
The logo should be in the upper right corner, just like in the viewer.

**Comment by afabiani** [comment]
Hi, I will into that. Not super-easy because the Print Module rebuilds the Map by itself, so this apparently small change requires a non trivial change to the printing library.

**Comment by afabiani** [comment]
As anticipated via mail, I added the UNESCO watermark on printing output. Not sure if I have to remove/fix the header and how to print the Layer/Map title.

**Comment by meyerch** [comment]
Thanks. Please find below some comments regarding the printing tool

1/ You can keep the header as is
2/ For the title, can you limit the number of characters to 100 characters (spaces included)? This is to avoid too long titles that would expand out of the header like this:
![printing-title.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d968aa788a4ab4ab051f5d665043761260ea62864c7b96aea1b7a055b5a4afa17095a46f9af892ba5b638708b590defc3714d36976345f3e5db55ea43a82a994e82bcbd8f4dc1ea3520e28c8d4d3f1c1755.PNG)

**Comment by meyerch** [comment]
4/ Please make the font of the abstract bigger. Also, please ensure that there is a larger margin on the left side of the abstract, to make sure that there is a bit more space between the abstract and the license. See below, highlighted in yellow:
![printing-legend-abstract.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d968aa788a4b346a358fe90644725603d16a22864c7af6aaf50740b0a0c0abe4b4a5a4dadad8d2ea2e06a218f5e0ebbd16d5c74c23d10a9be800da313f871d51bdaebe5c01982fa3737e68c854e3b1f041a81f85a30a4994bcf4abb.PNG)

**Comment by meyerch** [comment]
6/ Problem with zooming out/scale indicated/displayed result in the pdf. Comments and pictures will come tomorrow

**Comment by meyerch** [comment]
[Continuing on point 6/ here]. 
So, several issues: 
- in the PrintPreview, please ensure that the map is displayed accordingly to the scale selected through the drop menu. 
- in the outcome PDF, please ensure that the map always occupies the same space [to be clarified with pictures]

**Comment by meyerch** [comment]
From what I see on the DevInstance, nothing has changed in the outcome pdf of the PrintTool. 
Am I wrong?

**Comment by afabiani** [comment]
Not in terms of Layout (which can be modified. In terms of other issues most of them should be fixed. Putting it again into "In Progress" until the layout is not good with you (headers, map titles and so on...)

**Comment by meyerch** [comment]
I have tested a few times and I end up with the same layout that I reported (same fonts, alignements, place titles, etc.)

**Comment by afabiani** [comment]
Yep I see, some setting has been overwritten with the latest updates. Going to double check right now.

**Comment by meyerch** [comment]
Perfect, let me know when it is ok to check.

**Comment by afabiani** [comment]
@meyerch can you please double check now on DEV?

**Comment by meyerch** [comment]
Hi, I have just checked it, thanks . I will leave you some comments here tomorrow morning.

**Comment by meyerch** [comment]
Here are some comments on the printing tool: 
1/ can you limit the abstract to 700 characters (space included) ?

2/ can you add at the bottom of the page a margin ? (It should be as large as the current top margin. If need, you can reduce a bit the space between the  header and the map; and the space between the map and the abstract/license)
![printing_margin.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d968aa788d6b242b65af99a6b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84b1b68b49c1e93421ef838a463a190c0ac4.PNG)

**Comment by meyerch** [comment]
[continuing here]
3/ Can you make sure that the size of the PrintPreview frame is the same as the size of the frame in the PDF? Otherwise, it is misleading people on what will be the PDF outcome. See screenshots below for more clarity.
Here is the PrintPreview window:
![printing_frame-size1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d968aa788d6b951a550f5d93a4f3d767846ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1e13724e28a8e463b1e061f8ffa5c3cb2d4.PNG)

Here is the map in the outcome PDF:
![printing_frame-size2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d968aa788d6b951a550f5d93a4f3d767b46ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1e03724e28a8e463b1e06118bfe5936b2d4.PNG)

You can see that the size of what is shown is different. What the PrintPreview window shows should be will be the final map in the PDF, otherwise users will not understand.

**Comment by afabiani** [comment]
Hi @meyerch in the last message I guess is missing a screenshot. Is it ok for you if I create separate issues for this? Se we can estimate them separately and assign to different resources.

**Comment by meyerch** [comment]
Sure, no problem for the separate issue. 
Sorry the last screenshot is missing, I got caught up with an emergency and left this thread unfinished. Will add the missing image this afternoon
