### ISSUE TITLE
Mandatory fields in metadata

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#67]
I am adding this issue to Phase 1; it was considered as a low priority this summer (as commented in the spreadsheet) and forgotten about but this is still important as part of WP3. 

We would like to adjust which field is/isn't mandatory in the metadata, add a new field, and delete another one.
In the comments below are some schemes and explanations of what we are looking for. And here is the "legend" for those schemes:
![scheme-leged.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb9792268f86e483ecb846a01fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc824fc3ea3a23ef888d462c53.PNG)

Please, let me know if this is not clear.

**Comment by meyerch** [comment]
![scheme1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb9792268f86f8cda5fd53b652fa912a5265296b51fa2a74d1b67cb9447a545d5a18ac415b5f40fcf88c2da4a42062c80d55b98e30063e937f03a6aa8317b500bf20834c86b4b58e4ac4ed3f37aa.PNG)

![scheme2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb9792268f86fbcda5fd53b652fa912a5265296b51fa2a74d1b67cb9447a545d5a18ac415b5f40fcf88c2da4a42062c80d55b98e30063e937f03a6aa8318b500bf20834c86b4b58f45c9ed3d37aa.PNG)

![scheme3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb9792268f86facda5fd53b652fa912a5265296b51fa2a74d1b67cb9447a545d5a18ac415b5f40fcf88c2da4a42062c80d55b98e30063e937f03a6aa8318b500bf20834c86b4b58d4ec7ee3a37aa.PNG)

**Comment by meyerch** [comment]
1/Basic metadata
We would like you to move the "Edition"  field from the  "Optional metadata" page, to the "Basic metadata" page. This idea is for this field to become mandatory.

**Comment by meyerch** [comment]
2/ Location and Licences
a. Delete the "License" field as we don't need it.
b. Delete the "Restrictions" field as we don't need it. 
c. Move the "temporal extent start/end" field from the "Optional metadata" page to this page. So that it will become mandatory.
d. Move the "Data quality statement" field from this page to the "Optional metadata" page. So that it is no longer mandatory. 
e. Rename the "Restrictions other" field in "Restriction"

**Comment by meyerch** [comment]
3/ Optional metadata 
a. Move out the "edition" field to the 'basic metadata' page
b. Move out the "temporal extent start/end" to the 'Location and Licenses' page
c. Move in the "Data quality statement" from the 'Location and Licenses' page
d. Add the "DOI" field, with a textbox saying "a DOI will be added by Admin before publication"

**Comment by meyerch** [comment]
Perfect, thanks.
Accepted

**Comment by afabiani** [comment]
Done. Let me know if you need this field displayed also into the Info section.

![2017-10-19 11_45_59-wpdxcolombia_testpermissions — ihp-wins-dev.geo-solutions.it.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f9c2b8e603f50ccfc07c79722a6413b32f6886ec24b04f79080e300af9021c1f11bea4d068e5ef632ec94cd95d757d062c862056f5e6c102eb54fc3edc1adaabffd51085ac647ab9c891167a0c190ac9bd026ff5ca0fda52e44ee81c01a0163235b027337e42c21e752f6b6326aaf9d954959972e6eb4e7b0995baaeaf5400ab6ed9c00370665553ae2a34b1075b8d68915435.png)

**Comment by meyerch** [comment]
Yes, please display it in the Info section as well. Thanks!

**Comment by afabiani** [comment]
Done.

![2017-10-19 12_19_37-wpdxcolombia_testpermissions — ihp-wins-dev.geo-solutions.it.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f9c2b8e603f50fcfc5707974246413b32f6886ec24b04f79080e300af9021c1f11bea4d068e5ef632ec94cd95d757d062c862056f5e6c102eb54fc3edc1adaabffd51085ac647ab9c891167a0c190ac9bd026ff5ca0fda52e44ee81c01a0163235b027337e42c21e752f6b6326aaf9d954959972e6eb4e7b0995baaeaf5400ab6ed9ce0370665553ae2a3ab1035b8e699b5435.png)

**Comment by meyerch** [comment]
Thanl you. 
Accepted

**Comment by meyerch** [comment]
Reopening this since I forgot something (sorry for the inconvenience): 

For the Document's metadata, can you move the "Links to" field from the 'Basic metadata' page to the 'Optional metadata' page? So that the field is no longer mandatory.

**Comment by meyerch** [comment]
In the Wizard tool when editing metadata for a map, the "edition" field is both on the 'Basic metadata' page, and on the 'Optional metadata' page. Please, remove the field from the 'Optional metadata' page, so that it is only on the "Basic metadata' page.
![mpa-metadata.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5849b6e8f86bd8eedbe57a51fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc8248c1e03b22e1898e462c53.PNG)

**Comment by afabiani** [comment]
Ops, sorry. Removed.

**Comment by meyerch** [comment]
Also, please make sure that the 'Advanced edit' has the same fields as for the 'Wizard' tool. 
See screnshot below:
a. Remove the "Alternate field":
![advanced-edit-metadata1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e9908c228c80ac8ba4ba47ad49bd992c5226772810a27a32c9a138ad4d71040c1b5ca6535d5615a8fd8c2ff0e06d7588595dedd16e5f70c63c14aaba9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3e16011980f85a3da59a48da15.PNG)

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
In the "Advanced edit" : can you rename the "Restriction others" field in just "Restrictions" ?
![metadata-advanced-edit.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5918e228682bd8ea4be47b25cfe972c426a762d0db7693cc7f33ab0487e021b4d44be44510e10f8fc8d7df0e739728f0a0bedd26d5b74c73817aeaa9e0dfd50e474d412dcfce9c85ecafa3f25ed8a8a4f361a0d1d8bf75a35a39a5985.PNG)

**Comment by meyerch** [comment]
In the "Wizard" tool for the Document's metadata, can you move the "Links to" field from the 'Basic metadata' page to the 'Optional metadata' page? 
So that the field is no longer mandatory.

![metadata-doc-linkto.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5918e228682bd8ea4bb4ca710fc9d274d337c6b48e13b628ae92dbc56395b4d5a47fd155c5a40aaafd82ea4b36a708a5f0be9d16c5a72c42f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e7838b463a1b01118bfe5c27ed.PNG)

![metadata-doc-linkto2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5918e228682bd8ea4bb4ca710fc9d274d337c7b46ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28b874b371a00108afd5c33b2d4.PNG)

**Comment by afabiani** [comment]
done

**Comment by meyerch** [comment]
ok for the "links to" 

In the "Advanced edit" : can you rename the "Restrictions other" field in just "Restrictions" ?
![metadata-advanced-edit.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5918e228682bd8ea4be47b25cfe972c426a762d0db7693cc7f33ab0487e021b4d44be44510e10f8fc8d7df0e739728f0a0bedd26d5b74c73817aeaa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4f3619011981fc5433a39f5985.PNG)

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
ACCEPTED
