### ISSUE TITLE
Retrieving users to add in a group

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#69]
When adding members to a group, there is an issue with how users are retrieved in the 'User identifiers' list. 
The way users are retrieved is quite inconsistent.

See screenshot below.
When entering "es", all names are retrieved, even thoug they don't have "es" in their name: 
![group-members-search.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692cea48ae4bd46b64ebd872c4735702146ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28b87483a1c041a81f85e31b2d4.PNG)

Same here, with other letters: 
![group-members-search1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692cea48ae4bd46b64ebd872c4735702155e1673295f127b54778154d555ca948090b40f9fddf7df7b33e75dc5c0beed1695f75c33b13bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8f47391a07198ff75e37a68b06.PNG)

But sometimes it works well:
![group-members-search2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692cea48ae4bd46b64ebd872c4735702156e1673295f127b54778154d555ca948090b40f9fddf7df7b33e75dc5c0beed1695f75c33b13bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8f47391a071a8bff5b30a58b06.PNG)

But it seems that the system only search in the first name of the username. There are 2 users with "Test" as a last name (contributor.test & manager.test), but see what happens when I enter "tes"
![group-members-search3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ef86953692cea48ae4bd46b64ebd872c4735702157e1673295f127b54778154d555ca948090b40f9fddf7df7b33e75dc5c0beed1695f75c33b13bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8f47391a071b88fd5c3ca18b06.PNG)

So, is it possible to fix how names are retrieved? 
Will it takes a lot of time to set  the retrieving system so that it searches in the last name  as well as first name? If yes to this 2nd questoin, I guess we can keep the improvement for Phase 2

**Comment by meyerch** [comment]
There is exactly the same issue in the Permissions menu (only when retrieving Users. Retrieving process for Groups works perfectly). The retrieving process is quite inconsistent. It looks like when there is no match to the letters entered, the system retrieve any user which name contains some of those letters:

**Comment by afabiani** [comment]
Will have a look at this one in order to understand if it is a bug. My guess is that GeoNode is searching on wrong field or simply ignoring caps or something. Will provide you feedbacks ASAP.

**Comment by afabiani** [comment]
Can you please try again now? In GeoNode core there was a weird check. Basically the lookup was done by following the rules below:

Before:
 - username starts with letters (case)
 - first name contains letters
 - organization contains letters

Now (modified by me on IHP):
 - username contains letters (no case)

Let me know if can work like this.
