### ISSUE TITLE
Layer downloading : No SLD

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#70]
I noticed that when downloading a layer in a zipped shapefiles, only the following files are downloaded: 
- shx
- prj
- shp
- dbf
- txt
- cst

But the SLD is not download. Which means that if the user opens the dowloaded layer in a GIS software, he/she has to do all the work again to set the style. 

Can you make sure that the .SLD is included in the zip? Thanks

**Comment by afabiani** [comment]
Currently this is not easy to achieve since GeoNode relies on GeoServer WFS service to download the data. I need to evaluate this technically and see if GeoServer already makes available an option to package the zip along with the shapefile. If not we might need to change the endpoint and call another service instead.

**Comment by afabiani** [comment]
An additional comment about this; are you aware that not only it is possible to assign more than one style to a Layer but it is possible to download SLDs also by clicking over the style link
![Clipboard01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46cb989333808ca89dedef12e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513bb28814e80b6b58a4ec3eb3e24e08b8b5d73.jpg)

**Comment by meyerch** [comment]
Thanks for the info, I did not know! Since the style is downloadable through this way, packing it up within the ZIP is not a priority. 

However, This leads me to a new question: In all the "Style" box (on the right of each layer page), the style associated is called "None"... (screenshot1)
But when I click on it, it donwloads the correct style of the layer. (screenshot 2)

![style-layer2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb80832f87cea58ef0ba51f61fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8228a4584b3bc834dc1ee3d24e589874e2c53.PNG)

![style-layer2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb80832f87cea58ef0ba51f61fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc834dc1ee3d26e58c8d4e2c53.PNG)

**Comment by afabiani** [comment]
This is why somehow GeoNode and/or gsconfig Python library was not able to correctly parse the Style name or title from the XML. This is something that should be improved/fixed on GeoNode for sure.

**Comment by meyerch** [comment]
Hi, 
I am copy-pasting a comment I made on #21, since it is link to what you wrote here: 

"Is the process to upload sld for raster data the same as for vector data?
This is the first time I did the the test with a raster (sld was generaetd with the "sld4raster" plugin in qgis), and I ended up with the following message when uploading the sld:

![sld-raster.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb989e6e9082ba9becad01e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b22a8a4a85bfbf8b4cc3ed3a2de58b9d02.PNG)

**Comment by afabiani** [comment]
Fixed.

![2017-10-30 13_15_31-geonode-gwpollriskafriotest — ihp-wins-dev.geo-solutions.it.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f9c2baef03f50ecfc57c7974226403a6247e8ae72df2456c11000312ee181b0415aabbd074e2e37f349a8ebb49c1340734db7a48f2fb9f4bea47a477de1098f5e3d60984b1627ba495d60b2c021758cba00760f3dd59c24af342b01951a1176035b773347911941e762c6f6727aefadd449b9722f5e444700b91a9b1b80418b37dd0cd0874635c58ac2f3ab2005c8d658a0b.png)

**Comment by meyerch** [comment]
other question regarding the rasters: is it not possible to use the "Layer styles" tool on raster? I am trying to change colors on this layer (http://ihp-wins-dev.geo-solutions.it/layers/geonode:salinity) but nothing happens when I click on the different colors in the 'Layer style' window.

**Comment by afabiani** [comment]
@meyerch this issue should be also fixed now with the latest updates of GeoExplorer client (Printing and Style Editor). 

If more style are present for a Raster Layer, before editing the one to be edited must be selected on the topmost selectbox of the Style Editor.

**Comment by meyerch** [comment]
OK. 
I noticed that unlike for the vector layers, when editting style of a raster, I don't have the access to the "advanced" menu where limits of classes can be defined/change. 
Is it normal? 

See below, the option I have when editing the style of a raster (basically: only color rendering)
![style_raster.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb80832f87bcbb8efaab46b61fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bd8a49c6ec3523e78f8e472c53.PNG)

And the option when editing a vector:
![style_vector.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb80832f87bcbf8aeaab4cb61fbcd6395428792c07b7692ac7b671be462f545b0918fd445a5a12fcf98a2ba2b63d758c5e19f1c32f0e2a92624cf5f2d75dad0ba821834584b3bd8a49c6ec3525e4888b4e2c53.PNG)

**Comment by afabiani** [comment]
Hi, yes this is normal for two reasons mainly:

- The SLD contents for Rasters are differenct from Vectors; we don't have rules on Rasters but only color ramps

- The actual SLD editor of GeoNode has still some limitations and does not contain the whole functionalities that GeoServer would allow

**Comment by meyerch** [comment]
ok

**Comment by meyerch** [comment]
accepted
