### ISSUE TITLE
Non-approved users showing up in the list

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#71]
Is it possible to make sure that a user profile does not appear on the "Users" page [http://ihp-wins-dev.geo-solutions.it/people/?limit=100&offset=0] until his/her account has been activated by an admin? 

I have registered this user [http://ihp-wins-dev.geo-solutions.it/people/profile/test.test-tes/?limit=100&offset=0]. As you can see, anyone can access his profile, even though no admin as activated his account yet.

Thanks

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
perfect, thank you. 
ACCEPTED
