### ISSUE TITLE
URL link on the pages

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#72]
Is it possible to make URL link clickable on the "About us", "Terms of Use", "Get Started" pages? 

In put a link in the Terms of Use [http://ihp-wins-dev.geo-solutions.it/terms-of-use] (see screenshot below), but I cannot click the link.'

Or am I missing something in the HTML?

**Comment by meyerch** [comment]
![link.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e49d9428c0cfeb9ffbb049a15ee4d67304722a2800f77e2483e529ea102e075f5f4dac45585e41fafb9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abf09bd278b4783b0bf8f4fd2a5.PNG)

**Comment by afabiani** [comment]
Hi, yes, it looks to me that there is an HTML error.

<a ref="..."> should be <a href="..."> instead

**Comment by meyerch** [comment]
Many thanks.
ACCEPTED
