### ISSUE TITLE
issue with the Search menu

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#73]
In the search menu (on the left side of the page), the "Category"  is no longer working. For instance, if I select any of the different categories, I end up with all the layers available; no selection is made. And in the URL, I have this : http://ihp-wins-dev.geo-solutions.it/layers/?limit=100&offset=0&undefined=undefined

**Comment by meyerch** [comment]
![searc-categories.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb919b3181ceaa8efdba44ab4ff9913a046b313916ac217586f76ae5002e580e0b4aa9450e0915f9fb8c7da6b63f708e5c0ae8d76f4d68d47f40f2ecdd42e64bef62994597b7b4804dc5e8352ce3888a473f18051c9bb2.PNG)

**Comment by afabiani** [comment]
It should be a recent issue on GeoNode core (I was already working on that).
This should happens only when you click on the number, if you click on the category name the search works. (the same for other search fields)

**Comment by afabiani** [comment]
Done.

**Comment by meyerch** [comment]
accepted
