### ISSUE TITLE
Issue witht the 'search by name' menu with groups and people

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#74]
Hi, 

I just noticed that the 'search by name' option (on the left of the page) on the "Group" page and "Users" page, does not work anymore. 

What happens is that the search tool retrieves the users when entering letters, but nothing happens when I click 'Enter'.

See screenshots below

**Comment by meyerch** [comment]
I can't upload pictures here anymore apparently...

**Comment by afabiani** [comment]
- Just tried to upload pictures either for groups and people. It worked actually. I noticed that the avatar taken from gmail cannot be changed through. Could be this the case?

- I confirm the search issue. Going to fix.

**Comment by afabiani** [comment]
Fixed.

**Comment by meyerch** [comment]
Hi. Sorry, I meant that I could not upload pictures in this Waffle issue thread. Picture upload on WINS works well. 
As for the search issue: ACCEPTED
