### ISSUE TITLE
Check IHP-WINS UNESCO.org VM

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#75]
- [x] SSH Configuration
- [x] Disk resize
- [x] GeoNode Configuration
- [x] GeoServer Configuration
- [x] Set Forward Proxy
- [x] NewRelic Monitoring
- [ ] GeoServer Analytics
- [ ] Backup & Restore
- [ ] Setup Fail2Ban

**Comment by afabiani** [comment]
Done

**Comment by randomorder** [comment]
Waiting for feedback from Sysadmin to finalize

**Comment by randomorder** [comment]
Sysadmins at UNESCO have resized the disk today.  We'llmove on with fail2ban and Backup&Restore. For Analytics we still need outgoing traffic from the machine to be allowed
