### ISSUE TITLE
Missing Responsibles in the list

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#84]
An issue has just popped on the public and dev instances. 
In the Search menu on the right, in the "Responsibles" drop menu: 
- on the public instance, only najet.guefradj is now listed, although there are layers/documents from other responsibles
- on the dev instace, only gabin.archambault is listed

**Comment by meyerch** [comment]
![responsibles1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fa9189338d8dba86ebb346b70cb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98b4dc8e03e26e382884c370c48.PNG)

and

![responsibles2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fa9189338d8dba86ebb346b70fb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b4dc8e03e26ef8f8b4e3f0c48.PNG)

**Comment by afabiani** [comment]
Hi @meyerch currently najet appear to be the owner of 32 public layers and therefore is it normal that its name pops up among the Responsibles. I guess the best solution would be to review those layers, edit their metadata and update the owner accordingly.

Please let me know if you find some other discrepances.

**Comment by meyerch** [comment]
Hi! 
Sorry, my message was not clear. The issue is that on the public instance, najet.guefradj is the only responsible listed, although gabin.archambault, tales.carvalho-resende, lakshmi.seewsagur and myself also own many layers. --> our name are not in the list. 

On the dev instance, this time, only gabin.archambault is listed, although the same other users also own layers. 

I hope this clarifies the issue.

**Comment by afabiani** [comment]
Ok, will double check

**Comment by afabiani** [comment]
@meyerch fixed on production. Going to backport changes on DEV too. It was due to a wrong setting on limiting the number of resources produced by the GeoNode APIs.

Can you please double check?

**Comment by meyerch** [comment]
accepted. thanks
