### ISSUE TITLE
Legend pop up window by default in layers

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#85]
Can you ensure that there is no legend pop up window open by default when opening a layer [on both the dev and public instance] ? Thank you

**Comment by meyerch** [comment]
Since yesterday, all layer pages open up like this: 

![popuplegend.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f89b8a36928fac88ecb147e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513bb27814e80b7bd8244c3ee3825e48a885d73.PNG)

**Comment by afabiani** [comment]
Done

**Comment by meyerch** [comment]
accepted
