### ISSUE TITLE
printing: size and frame for the PrintPreview and PDF

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#86]
following issue #64, I am opening a dedicated issue to this problem

**Comment by meyerch** [comment]
3/ Can you make sure that the size of what is shown in the PrintPreview frame is the same as the size of what ends up in the PDF? Otherwise, it is misleading people on what will be the PDF outcome. See screenshots below for more clarity.
Here is the PrintPreview window:
![printing_frame-size1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d968aa788d6b951a550f5d93a4f3d767846ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28a8e463819011881fe5c3cb2d4.PNG)

Here is the map in the outcome PDF:
![printing_frame-size2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46f886932d968aa788d6b951a550f5d93a4f3d767b46ef696097ec22ba416f43554d4ba5100c5b41f8afdf7aa3b439268a5c08edd56d5e71c03f03b0aac04ee155e57dd205d0f4ae805ec1e03724e28a8e463819011a81ff5e3cb2d4.PNG)

You can see that the size of what is shown is different. What the PrintPreview window shows should be will be the final map in the PDF, otherwise users will not understand.
It looks like the PDG map is zoomed out a bit from the PrintPreview window. Both should be identical.

This leads me to the follwing point:
4/ Can you resize both the PrintPreview window and the map frame in the PDF to avoid the frieze to show in the PDF map? We want the frame to be of the extent of the world map tiles, so that at scale 1:250,000,000 no object/country can be show 2 times in the print preview, no matter how the user position the map.
See what we have in mind hereunder:

**Comment by meyerch** [comment]
This leads me to the following point:

Can you resize both the PrintPreview window and the map frame in the PDF to avoid the frieze to show in the PDF map? We want the frame to be of the extent of the world map tiles, so that at scale 1:250,000,000 no object/country can be show 2 times in the print preview, no matter how the user position the map.

See what we have in mind hereunder:

**Comment by afabiani** [comment]
Updated the dimensions. The outcomes are like the following:

## Wide
![2017-12-22 18_59_06-lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor i](https://user-images.githubusercontent.com/1278021/34307963-17740b66-e74b-11e7-9ac4-435eadf1dcac.png)

![2017-12-22 19_00_05-lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor i](https://user-images.githubusercontent.com/1278021/34307966-19f7c904-e74b-11e7-9e93-35144f386466.png)

## A4

![2017-12-22 19_01_15-lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor i](https://user-images.githubusercontent.com/1278021/34307973-211f5a4e-e74b-11e7-8c12-1752a5956931.png)

![2017-12-22 19_04_21-lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor i](https://user-images.githubusercontent.com/1278021/34307976-2426545e-e74b-11e7-9ca8-7b15853065b3.png)

**Comment by meyerch** [comment]
Perfect, thanks. 
Accepted
