### ISSUE TITLE
Impossible to upload layers

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#94]
I am trying to uplad layers to test the TimeSerie but the upload always fails. 
I end up with an "unexpected error" message.

**Comment by meyerch** [comment]
![upload-layers.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fd84962c8387e483e8a646b64eb2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98b4fc6e8382ce1888c4d3e0c48.PNG)

**Comment by afabiani** [comment]
@meyerch can you please send me via email the zip of the original shapefile?

**Comment by meyerch** [comment]
sure, i am doing it right now

**Comment by meyerch** [comment]
Hi, I still have the same issue when uploading shapefile to the dev instance...
![uploading-layer-error.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fd84962c8387a081eef24fa544f586644335612616e1673295f127b54778154d555ca948090b40f9fddf7df7b33e75dc5c0beed1695f75c33b13bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8e4a3e16041f8cf95835a58b06.PNG)

**Comment by meyerch** [comment]
ok
