### ISSUE TITLE
Impossible to access metadata

### ISSUE THREAD

**Issue by meyerch** [geosolutions-it/unesco-ihp#97]
ISSUE ON BOTH THE DEV AND PUBLIC INSTANCE !

When trying to access metadata detail, I end up on an error page. This is because the URL that comes out is each time is http://ihp-wins.unesco.org/layers//metadata_detail. You  will notice that the name of the layer is missing from the URL, and should be between the 2 "//" 

For exemple, when trying to access metadata detail for this layer: http://ihp-wins.unesco.org/layers/geonode:wpif, I end up on this page: http://ihp-wins.unesco.org/layers//metadata_detail. 
However, if I add the name of the layer to the URL (which results in http://ihp-wins.unesco.org/layers/geonode:wpif/metadata_detail), the metadata page is correctly displayed. 

Can you fix this issue? Thank you

**Comment by afabiani** [comment]
@meyerch I noticed that this issue seem to affect old layers. New ones looks working as expected. I'm on it. Will send updates ASAP.

**Comment by meyerch** [comment]
Thank you, everything seems to be back to normal. 
I am archiving this one.
